### ISSUE TITLE
[bug]: force closed channel stuck in pending but already swept

### ISSUE THREAD

**Issue by rsafier** [lightningnetwork/lnd#10351]
### Pre-Submission Checklist

- [x] I have searched the existing issues and believe this is a new bug.
- [x] I am not asking a question about how to use lnd, but reporting a bug (otherwise open a discussion).

### LND Version

0.19.3-beta commit=v0.19.3-beta

### LND Configuration

lnd.conf:
```
[Application Options]
# Public network name
alias=node-alias

# cpu profiling port
# curl localhost:1024/debug/pprof/.
profile=1024

# prometheus
prometheus.enable=true
prometheus.listen=0.0.0.0:8989

# Public hex color
color=#141414

# Log levels
debuglevel=CNCT=debug,HSWC=debug

# Public P2P IP
externalip=1.2.3.4
#a
# Set the maximum amount of commit fees in a channel
max-channel-fee-allocation=0.2

# Set the max tiemout blocks of a payment
max-cltv-expiry=5000

# Pending channel limit
maxpendingchannels=10

# Min inbound channel limit
minchansize=5000000

# Max inbound channel limit (wumbo)
maxchansize=200000000

# gRPC socket binding
rpclisten=0.0.0.0:10009

# REST port
restlisten=0.0.0.0:8080

# p2p port
listen=0.0.0.0:9735

# Enable free list syncing for the default bbolt database. This will decrease
# start up time, but can result in performance degradation for very large
# databases, and also result in higher memory usage. If "free list corruption"
# is detected, then this flag may resolve things.
sync-freelist=false

# Avoid high startup overhead
stagger-initial-reconnect=true

# Coin selection optimization
coin-selection-strategy=random

# TLS certificate IP
tlsextraip=1.2.3.4
# private IP for GRPC for local network
tlsextraip=4.5.6.7

tlsextradomain=xxx.yyy.zzz
# whether or not it tries to automatically connect to peers
nobootstrap=false

# Cancel invoices that are expired, allows better cleanup
gc-canceled-invoices-on-startup=true
gc-canceled-invoices-on-the-fly=false

allow-circular-route=false
# For future toggles
accept-keysend=true
# accept-amp=true

requireinterceptor=false
store-final-htlc-resolutions=false
rejecthtlc=false
keep-failed-payment-attempts=false
default-remote-max-htlcs=200
; The maximum fee rate in sat/vbyte that will be used for commitments of
; channels of the anchors type. Must be large enough to ensure transaction
; propagation (default: 10)
max-commit-fee-rate-anchors=100

[caches]
; The duration that the response to DescribeGraph should be cached for. Setting
; the value to zero disables the cache. (default: 1m)
caches.rpc-graph-cache-duration=5m

[db]
; The selected database backend. The current default backend is "bolt". lnd
; also has experimental support for etcd, a replicated backend.
db.backend=bolt
db.prune-revocation=true
db.no-rev-log-amt-data=true
# db.backend=postgres

# COMMENTED OUT FOR REFERENCE*****
# [postgres]
# db.postgres.dsn=
# db.postgres.timeout=
# db.postgres.maxconnections=
[postgres]

[bolt]
# Auto compacting the DB
# defaults to 1week min age to compact db
db.bolt.auto-compact=true
[rpcmiddleware]

; Enable the RPC middleware interceptor functionality.
rpcmiddleware.enable=true

; Time after which a RPC middleware intercept request will time out and return
; an error if it hasn't yet received a response.
rpcmiddleware.intercepttimeout=25s
 
; rpcmiddleware.addmandatory=other-mandatory-middleware
[protocol]
# Wumbo (large channel sizes than 16.7M sats protocol limit)
protocol.wumbo-channels=true
protocol.option-scid-alias=true
protocol.zero-conf=true

# Set to enable support for RBF based coop close.
protocol.rbf-coop-close=1

[Bitcoin]
# Turn on Bitcoin mode
bitcoin.active=1

# Set the channel confs to wait for channels
bitcoin.defaultchanconfs=3

# Forward fee rate in parts per million
bitcoin.basefee=1000
bitcoin.feerate=10000
bitcoin.timelockdelta=144
# Set bitcoin.testnet=1 or bitcoin.mainnet=1 as appropriate
bitcoin.mainnet=true
bitcoin.testnet=false
bitcoin.signet=false
bitcoin.regtest=false
bitcoin.signetchallenge=
# Set backing node, bitcoin.node=neutrino or bitcoin.node=bitcoind
bitcoin.node=bitcoind


[Bitcoind]

bitcoind.rpchost=to-load-balancer-for-bitcoind.elb.us-east-1.amazonaws.com
# Set the password to what the auth script said
bitcoind.rpcpass=xxx

# Set the username
bitcoind.rpcuser=xxx

# for future use switching off ZMQ to Polling
bitcoind.rpcpolling=true
bitcoind.blockpollinginterval=1m
bitcoind.txpollinginterval=1m

[routerrpc]
# Set default chance of a hop success
routerrpc.apriori.hopprob=0.40

# Set minimum desired savings of trying a cheaper path
routerrpc.attemptcost=10

# Set the number of historical routing records
routerrpc.maxmchistory=10000

# Set the min confidence in a path worth trying
routerrpc.minrtprob=0.001

# Set the time to forget past routing failures
routerrpc.apriori.penaltyhalflife=24h0m0s
routerrpc.estimator=apriori

[healthcheck] 
healthcheck.chainbackend.timeout=120s
```

### Backend Version

Bitcoin Core 30.0

### Backend Configuration

bitcoin.conf:
```
deprecatedrpc=warnings
rpcallowip=100.0.0.0/16
rpcbind=0.0.0.0
datadir=/xxx/bitcoind/data
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
# Set publish hash block outbound message high water mark.
zmqpubhashblockhwm=10000
# Set publish hash transaction outbound message high water mark.
zmqpubhashtxhwm=10000
# Set publish raw block outbound message high water mark.
zmqpubrawblockhwm=10000
# Set publish raw transaction outbound message high water mark.
zmqpubrawtxhwm=10000
# Set publish hash sequence message high water mark.
zmqpubsequencehwm=10000
listen=false
server=1
txindex=1
blockfilterindex=1
maxmempool=300
disablewallet=1
# debug=rpc
dbcache=4096
# limits to 1GB per day given back to peers
maxuploadtarget=1000
rpcuser=xxx
rpcpassword=xxx
rpcworkqueue=1024
# Maximum per-connection receive buffer (KiB).
maxreceivebuffer=10000
# Maximum per-connection send buffer (KiB).
maxsendbuffer=5000
```

### OS/Distribution

Linux ip.ec2.internal 6.1.156-177.286.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 21 22:16:56 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

### Bug Details & Steps to Reproduce

We restarted the `lnd` process in order to update host node and do compaction on boltdb. Upon `lnd` becoming ready noticed that a recently force closed channel showed up as pending force closure tho with a maturity of >-2400 blocks and limbo balance. 

### Expected Behavior

Upon restart of `lnd` prior closed and swept channels should not reappear in the `pending` state.

### Debug Information

Issue appears in pendingchannels output, reporting limbo balance and pending FC.
```bash 
$ lncli pendingchannels
{
    "total_limbo_balance": "832119",
    "pending_open_channels": [],
    "pending_closing_channels": [],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "031a01e29587952eda0ed5d10c4e79bf0fc88d61aeae89e8a7ea7c036badb8c793",
                "channel_point": "f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2",
                "capacity": "5000000",
                "local_balance": "832119",
                "remote_balance": "4166889",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false,
                "memo": "",
                "custom_channel_data": ""
            },
            "closing_txid": "4b7464d7a4422e32d587aa3c587eaaf72195944d4a4ec50c359ef92f7596c40e",
            "limbo_balance": "832119",
            "maturity_height": 919999,
            "blocks_til_maturity": -2493,
            "recovered_balance": "0",
            "pending_htlcs": [],
            "anchor": "LOST"
        }
    ],
    "waiting_close_channels": []
}
```
but we show no pendingsweeps
```bash
$ lncli wallet pendingsweeps
{
    "pending_sweeps": []
}
```
and we do see the sweep of limbo funds weeks ago via `lncli wallet listsweeps` txid: `e1d6c4267ff64d0f248331bc3624c034e85f355e30e99e7f5a27ef0d8c201721` and funds were subsequently spent, so all signs are this is a reporting issue, no funds are stuck or unclaimed as far as I can tell.

### Environment

`lnd` runs official docker image into EC2 VM. We run in `rpcpolling` mode under `bitcoind`, that points to a load balancer, multiple backing nodes round-robin accessed. Nodes are peered together, and also have their mempool's actively synced to avoid discrepancies.

**Comment by bitromortac** [comment]
Right, all outputs are swept, anchors appear to have been swept by an external party, which led to issues recognizing the full resolution of the channel in the past, but here it seems to not recognize that `to_local` was already swept. If you could share logs (can do that privately via slack) with `debuglevel=SWPR=debug,CNCT=debug,BTCN=debug,NTFN=debug,LNWL=debug,CHNF=debug` on restart that would be helpful.

**Comment by ziggie1984** [comment]
should be fixed with: https://github.com/lightningnetwork/lnd/pull/10387

**Comment by bitromortac** [comment]
So this will be released with 0.20.1, does the issue still exist @rsafier? It would be nice if you could test that upgrading to 0.20.1 fixes the issue (when it is out).

**Comment by rsafier** [comment]
> So this will be released with 0.20.1, does the issue still exist [@rsafier](https://github.com/rsafier)? It would be nice if you could test that upgrading to 0.20.1 fixes the issue (when it is out).

Condition remains unchanged. We plan on upgrading once 0.20.1 is released will report back at that time.

**Comment by saubyk** [comment]
Closing this issue as the fix is merged and should be available with 20.1. Feel free to reopen if the issue remains unaddressed.

**Comment by rsafier** [comment]
Reopening issue after applying 0.20.1 patch we still have issue present.

**Comment by ziggie1984** [comment]
@rsafier Thanks for confirming the issue persists on v0.20.1. To narrow down the root cause we need to see what's happening on restart when the resolver tries to re-detect the already-swept output. Could you set the following debug levels, restart, and share the relevant logs?

### Debug levels

```
debuglevel=CNCT=debug,SWPR=debug,NTFN=debug
```

- `CNCT` = contract court (channel arbitrator + resolvers)
- `SWPR` = sweeper (handles sweeping outputs back to wallet)
- `NTFN` = chain notifications (spend/confirmation detection)

### What we expect to happen on restart

Since all outputs are already swept on-chain, the following should happen on restart:

1. The arbitrator starts in `StateWaitingFullResolution` and finds unresolved contract(s) in the DB
2. It relaunches the resolver(s), which offer the already-spent input to the sweeper
3. The sweeper registers a spend notification (`RegisterSpendNtfn`) for the input
4. The chain backend detects the historical spend and fires the notification
5. The resolver receives the result (either success or `ErrRemoteSpend`) and marks itself resolved
6. The channel transitions to `StateFullyResolved`

Something in this chain is breaking. The logs will tell us exactly where.

### What to grep for

After restarting, filter logs for the stuck channel's funding outpoint. Here's the sequence of log lines you should see, and what it means if any are missing:

**Step 1 — Arbitrator finds unresolved contracts:**
```
ChannelArbitrator(<chanpoint>): starting state=StateWaitingFullResolution, trigger=...
ChannelArbitrator(<chanpoint>): still have unresolved contract: *contractcourt.<type>
ChannelArbitrator(<chanpoint>): relaunching N contract resolvers
```
The `<type>` tells us which resolver is stuck (e.g. `commitSweepResolver`, `htlcTimeoutResolver`).

**Step 2 — Resolver launches and offers input to sweeper:**
```
launching resolver...
sweeping commit output <witness_type> using budget=...
Registered sweep request at block N: out_point=<outpoint>
```
If `launching resolver` is missing or you see `unable to launch contract resolver`, the resolver failed to start.

**Step 3 — Sweeper detects the historical spend:**
```
Delivering spend ntfn for <outpoint>
Input=<outpoint> was spent by remote or third party in tx=<txid>
```
**If these lines are missing**, the spend notification never fired. This would mean the chain backend didn't detect that the output was already spent, and the resolver is waiting forever.

**Alternatively**, if the sweeper processes a new block before the spend notification arrives, it may try to sweep the already-spent input and hit:
```
Tx <txid> missing inputs, it's likely the input has been spent by others
```
If you see this **without** the `Delivering spend ntfn` line above, the fee bumper detected the spent output first. This is a suspected problem path — the `commitSweepResolver` currently doesn't handle `ErrInputMissing`, which would cause it to exit with an error.

**Step 4 — Resolver completes (or fails):**

Success case:
```
local commitment output fully resolved by sweep tx: <txid>
marking contract *contractcourt.commitSweepResolver fully resolved
ChannelArbitrator(<chanpoint>): a contract has been fully resolved!
ChannelArbitrator(<chanpoint>): all contracts fully resolved, exiting
```

Failure case:
```
ChannelArbitrator(<chanpoint>): unable to progress *contractcourt.commitSweepResolver: <error>
```
The `<error>` here is the key — it tells us exactly which error the resolver received that it couldn't handle.

### Summary

We suspect the resolver is either (a) never receiving the spend notification, or (b) receiving an error from the sweeper (`ErrInputMissing`) that it doesn't handle correctly. The logs above will confirm which case it is.

Feel free to share privately via Slack if preferred.

**Comment by rsafier** [comment]
Error is **unable to sweep input: input no longer exists**

pending_channels
```json
{
    "total_limbo_balance": "832449",
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "031a01e29587952eda0ed5d10c4e79bf0fc88d61aeae89e8a7ea7c036badb8c793",
                "channel_point": "f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2",
                "capacity": "5000000",
                "local_balance": "832119",
                "remote_balance": "4166889",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false,
                "memo": "",
                "custom_channel_data": ""
            },
            "closing_txid": "4b7464d7a4422e32d587aa3c587eaaf72195944d4a4ec50c359ef92f7596c40e",
            "limbo_balance": "832449",
            "maturity_height": 919999,
            "blocks_til_maturity": -16969,
            "recovered_balance": "0",
            "pending_htlcs": [],
            "anchor": "LIMBO"
        }
    ]
}
```

LOGS AFTER SETTINGS `debuglevel=CNCT=debug,SWPR=debug,NTFN=debug`:

```bash
cat logs/bitcoin/mainnet/lnd.log | grep 'f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2'
2026-02-16 21:08:57.862 [INF] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): starting state=StateWaitingFullResolution, trigger=chainTrigger, triggerHeight=919399
2026-02-16 21:08:57.862 [DBG] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): attempting state step with trigger=chainTrigger from state=StateWaitingFullResolution at height=919399
2026-02-16 21:08:57.862 [INF] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): still awaiting contract resolution
2026-02-16 21:08:57.865 [DBG] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): still have unresolved contract: *contractcourt.commitSweepResolver
2026-02-16 21:08:57.865 [DBG] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): terminating at state=StateWaitingFullResolution
2026-02-16 21:08:57.866 [INF] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): relaunching 1 contract resolvers
2026-02-16 21:08:57.866 [DBG] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): *contractcourt.anchorResolver(4b7464d7a4422e32d587aa3c587eaaf72195944d4a4ec50c359ef92f7596c40e:1): launching resolver...
2026-02-16 21:08:57.880 [DBG] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): *contractcourt.commitSweepResolver(4b7464d7a4422e32d587aa3c587eaaf72195944d4a4ec50c359ef92f7596c40e:2): launching resolver...
2026-02-16 21:08:57.881 [DBG] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): *contractcourt.commitSweepResolver(4b7464d7a4422e32d587aa3c587eaaf72195944d4a4ec50c359ef92f7596c40e:2): isDelayedOutput=true, isLocalCommitTx=true
2026-02-16 21:08:57.881 [INF] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): *contractcourt.commitSweepResolver(4b7464d7a4422e32d587aa3c587eaaf72195944d4a4ec50c359ef92f7596c40e:2): sweeping commit output CommitmentTimeLock using budget=0.00416060 BTC
2026-02-16 21:09:02.367 [DBG] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): received new block: height=936968, processing...
2026-02-16 21:09:02.367 [INF] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): skipping reading close events in state=StateWaitingFullResolution
2026-02-16 21:09:02.527 [ERR] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): *contractcourt.commitSweepResolver(4b7464d7a4422e32d587aa3c587eaaf72195944d4a4ec50c359ef92f7596c40e:2): unable to sweep input: input no longer exists
2026-02-16 21:09:02.527 [ERR] CNCT: ChannelArbitrator(f075fc8ed00a3bce2de89279e5ade6f7bf02d3a33f1edd6b34f9e934070ab94c:2): unable to progress *contractcourt.commitSweepResolver: input no longer exists
```

**Comment by litbot-9000** [comment]
Consolidating related issue here. The following has been closed as a duplicate:

- #8366 — Detailed report of the same class of bug: restoring a node with SCB after a counterparty force-closed long ago creates a `pending_force_close` channel with negative `blocks_til_maturity` that never resolves. On-chain funds are recovered correctly but the pending entry persists forever. Includes an itest demonstrating the issue and a discussion of possible resolution strategies (auto-detect and remove, add an RPC to remove, filter in listing, etc).

**Comment by ZZiigguurraatt** [comment]
I'm running the docker image `lightninglabs/lndinit:v0.1.35-beta-lnd-v0.21.0-beta.rc1`. I think I may have the same issue or a related issue.

### Steps to **reproduce** on regtest:

1. Open channel between Alice and bob
2. Bob goes offline
3. Channel goes inactive
4. Alice force closes channel.
5. Quick mine ~2,100 blocks
6. Blocks to maturity goes negative and continues to get more negative.

Some relevant log file lines

```
2026-05-07 17:10:25.144 [INF] SWPR: Registered sweep request at block 311: out_point=e09335f43df03a060b9a0814ab6e004c24a026c4e59149003280cf8800418e88:1, witness_type=CommitmentAnchor, amount=0.00000330 BTC, deadline=1319, state=Init, params=(startingFeeRate={false 0}, immediate=false, exclusive_group=264982302359553, budget=0.00000330 BTC, deadline=none)
2026-05-07 17:10:25.434 [INF] NTFN: Historical spend dispatch finished for request outpoint=e09335f43df03a060b9a0814ab6e004c24a026c4e59149003280cf8800418e88:1, script=0 a809c06de70fc94a8dc651a2ee485830c941ef988fb2e7fd6d4b4c8f0916c922 (start=311 end=311) with details: <nil>
2026-05-07 17:10:25.446 [INF] SWPR: Registered sweep request at block 311: out_point=8a16f607a015c106cc10d23072b295a23533d5069bcb206652bc6f6c2276f0ec:1, witness_type=CommitmentAnchor, amount=0.00000330 BTC, deadline=1319, state=Init, params=(startingFeeRate={false 0}, immediate=false, exclusive_group=264982302359553, budget=0.00000330 BTC, deadline=none)
2026-05-07 17:10:25.493 [INF] CNCT: ChannelArbitrator(9bf68030298ca806332bc5db6d1e3de7438bb6216d19210c0f63b6a3e1aca738:1): trigger userTrigger moving from state StateCommitmentBroadcasted to StateCommitmentBroadcasted
2026-05-07 17:10:25.494 [INF] PEER: Waiting for confirmation of close of ChannelPoint(9bf68030298ca806332bc5db6d1e3de7438bb6216d19210c0f63b6a3e1aca738:1) with txid: 8a16f607a015c106cc10d23072b295a23533d5069bcb206652bc6f6c2276f0ec
2026-05-07 17:10:25.494 [INF] NTFN: New confirmation subscription: conf_id=5, txid=8a16f607a015c106cc10d23072b295a23533d5069bcb206652bc6f6c2276f0ec, num_confs=1 height_hint=311
2026-05-07 17:10:25.512 [INF] SWPR: Registered sweep request at block 311: out_point=e68ceabf71641af0ba42a1baf738aad8c722fe7f26beee1277dd6a3512fa356e:1, witness_type=CommitmentAnchor, amount=0.00000330 BTC, deadline=1319, state=Init, params=(startingFeeRate={false 0}, immediate=false, exclusive_group=264982302359553, budget=0.00000330 BTC, deadline=none)
```

```
2026-05-07 17:15:04.012 [INF] NTFN: New block: height=1729, sha=3de90b1ba54ebd48f6ae403471876425f5cee20f2d62d3183e6dd93b047d1f02
2026-05-07 17:15:04.018 [INF] SWPR: Change amt 0.00000001 BTC below dustlimit 0.00000330 BTC, not adding change output
2026-05-07 17:15:04.018 [ERR] SWPR: Initial broadcast failed: create RBF-compliant tx: create sweep tx: tx has no output
2026-05-07 17:15:04.018 [ERR] SWPR: Removing monitor record=959, tx=0000000000000000000000000000000000000000000000000000000000000000, due to err: create RBF-compliant tx: create sweep tx: tx has no output
2026-05-07 17:15:04.019 [WRN] SWPR: Failed to publish input 8a16f607a015c106cc10d23072b295a23533d5069bcb206652bc6f6c2276f0ec:1
2026-05-07 17:15:04.019 [INF] CNCT: ChannelArbitrator(9bf68030298ca806332bc5db6d1e3de7438bb6216d19210c0f63b6a3e1aca738:1): skipping reading close events in state=StateWaitingFullResolution
2026-05-07 17:15:04.036 [WRN] SWPR: Deadline is 1 blocks behind current height 1320
2026-05-07 17:15:04.036 [INF] SWPR: Change amt 0.00000001 BTC below dustlimit 0.00000330 BTC, not adding change output
2026-05-07 17:15:04.036 [ERR] SWPR: Initial broadcast failed: create RBF-compliant tx: create sweep tx: tx has no output
2026-05-07 17:15:04.037 [ERR] SWPR: Removing monitor record=960, tx=0000000000000000000000000000000000000000000000000000000000000000, due to err: create RBF-compliant tx: create sweep tx: tx has no output
2026-05-07 17:15:04.037 [INF] CNCT: ChannelArbitrator(9bf68030298ca806332bc5db6d1e3de7438bb6216d19210c0f63b6a3e1aca738:1): skipping reading close events in state=StateWaitingFullResolution
2026-05-07 17:15:04.037 [WRN] SWPR: Failed to publish input 8a16f607a015c106cc10d23072b295a23533d5069bcb206652bc6f6c2276f0ec:1
2026-05-07 17:15:04.053 [INF] NTFN: New block: height=1730, sha=14d9e45ac56870340727122dc86da74f3bcad980b6cad36a75fa4915b124e03c
2026-05-07 17:15:04.055 [WRN] SWPR: Deadline is 2 blocks behind current height 1321
2026-05-07 17:15:04.056 [INF] SWPR: Change amt 0.00000001 BTC below dustlimit 0.00000330 BTC, not adding change output
2026-05-07 17:15:04.056 [ERR] SWPR: Initial broadcast failed: create RBF-compliant tx: create sweep tx: tx has no output
2026-05-07 17:15:04.056 [ERR] SWPR: Removing monitor record=961, tx=0000000000000000000000000000000000000000000000000000000000000000, due to err: create RBF-compliant tx: create sweep tx: tx has no output
2026-05-07 17:15:04.056 [INF] CNCT: ChannelArbitrator(9bf68030298ca806332bc5db6d1e3de7438bb6216d19210c0f63b6a3e1aca738:1): skipping reading close events in state=StateWaitingFullResolution
2026-05-07 17:15:04.056 [WRN] SWPR: Failed to publish input 8a16f607a015c106cc10d23072b295a23533d5069bcb206652bc6f6c2276f0ec:1
2026-05-07 17:15:04.075 [WRN] SWPR: Deadline is 3 blocks behind current height 1322
2026-05-07 17:15:04.076 [INF] SWPR: Change amt 0.00000001 BTC below dustlimit 0.00000330 BTC, not adding change output
2026-05-07 17:15:04.076 [ERR] SWPR: Initial broadcast failed: create RBF-compliant tx: create sweep tx: tx has no output
2026-05-07 17:15:04.076 [ERR] SWPR: Removing monitor record=962, tx=0000000000000000000000000000000000000000000000000000000000000000, due to err: create RBF-compliant tx: create sweep tx: tx has no output
2026-05-07 17:15:04.076 [WRN] SWPR: Failed to publish input 8a16f607a015c106cc10d23072b295a23533d5069bcb206652bc6f6c2276f0ec:1
2026-05-07 17:15:04.077 [INF] CNCT: ChannelArbitrator(9bf68030298ca806332bc5db6d1e3de7438bb6216d19210c0f63b6a3e1aca738:1): skipping reading close events in state=StateWaitingFullResolution
2026-05-07 17:15:04.085 [INF] NTFN: New block: height=1731, sha=6a007197bbcf31690ffef0556692c631eb34d1c0867eb97d3a4d21eb0a8b4c1f
2026-05-07 17:15:04.090 [WRN] SWPR: Deadline is 4 blocks behind current height 1323
2026-05-07 17:15:04.092 [INF] SWPR: Change amt 0.00000001 BTC below dustlimit 0.00000330 BTC, not adding change output
2026-05-07 17:15:04.092 [ERR] SWPR: Initial broadcast failed: create RBF-compliant tx: create sweep tx: tx has no output
2026-05-07 17:15:04.092 [ERR] SWPR: Removing monitor record=963, tx=0000000000000000000000000000000000000000000000000000000000000000, due to err: create RBF-compliant tx: create sweep tx: tx has no output
2026-05-07 17:15:04.092 [WRN] SWPR: Failed to publish input 8a16f607a015c106cc10d23072b295a23533d5069bcb206652bc6f6c2276f0ec:1
2026-05-07 17:15:04.092 [INF] CNCT: ChannelArbitrator(9bf68030298ca806332bc5db6d1e3de7438bb6216d19210c0f63b6a3e1aca738:1): skipping reading close events in state=StateWaitingFullResolution
2026-05-07 17:15:04.108 [WRN] SWPR: Deadline is 5 blocks behind current height 1324
2026-05-07 17:15:04.108 [INF] SWPR: Change amt 0.00000001 BTC below dustlimit 0.00000330 BTC, not adding change output
2026-05-07 17:15:04.108 [ERR] SWPR: Initial broadcast failed: create RBF-compliant tx: create sweep tx: tx has no output
```


### Steps to (usually) **avoid** on regtest

1. Open channel between Alice and bob
2. Bob goes offline
3. Channel goes inactive
4. Alice force closes channel.
5. Quick mine ~1,900 blocks
6. Slow mine the remaining blocks at 2 seconds/block
7. Blocks to maturity goes to ~-4 blocks and then channel is fully closed (I think the short negative blocks to maturity here might be to check for and handle re-orgs if they happen).

**Comment by ZZiigguurraatt** [comment]
> ### Steps to (usually) **avoid** on regtest
> 
>     1. Open channel between Alice and bob
> 
>     2. Bob goes offline
> 
>     3. Channel goes inactive
> 
>     4. Alice force closes channel.
> 
>     5. Quick mine ~1,900 blocks
> 
>     6. Slow mine the remaining blocks at 2 seconds/block
> 
>     7. Blocks to maturity goes to ~-4 blocks and then channel is fully closed (I think the short negative blocks to maturity here might be to check for and handle re-orgs if they happen).

I've played around with steps 5 and 6 step a bit more and it seems like it requires https://github.com/lightningnetwork/lnd/blob/50eb0d1466f8da297a20a055d8041b2a65ae1f4a/lnrpc/lightning.proto#L2112-L2115 to be in the synced state _before_ `blocks_til_maturity` reaches 0 to avoid getting borked.

**Comment by ZZiigguurraatt** [comment]
Did some more triage in my testing environment with @ziggie1984 offline on this issue. What was discovered:

Here we are missing the notification:

```
2026-05-07 19:30:38.277 [WRN] SWPR: Failing record=1990: found orphan inputs: 0a03386da1e38005c64f246461e63661e079767064bf8ddaacc91fa7cb20a3d8:3 (CommitmentTimeLock)
2026-05-07 19:30:38.422 [ERR] SWPR: Failed to sweep input: 0a03386da1e38005c64f246461e63661e079767064bf8ddaacc91fa7cb20a3d8:3 (CommitmentTimeLock), error: input no longer exists
2026-05-07 19:30:38.437 [DBG] SWPR: Canceling spend ntfn for 0a03386da1e38005c64f246461e63661e079767064bf8ddaacc91fa7cb20a3d8:3
2026-05-07 19:30:38.439 [DBG] SWPR: Removing input(State=Fatal) 0a03386da1e38005c64f246461e63661e079767064bf8ddaacc91fa7cb20a3d8:3 from sweeper
```

and it is a race condition in the sweeper. Fixing it might be more involved because the design is restricting us here. We will have to fix it a bit later with a larger refactor of the sweeper.
