### ISSUE TITLE
Channel always inactive - Logs seems ok

### ISSUE THREAD

**Issue by danbadjar** [lightningnetwork/lnd#2121]
### Background
Hello I have an open channel which is always is state inactive

```
            "active": false,
            "remote_pubkey": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
            "channel_point": "617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0",
            "chan_id": "602210215139606528",
            "capacity": "1000000",
            "local_balance": "998915",
            "remote_balance": "0",
            "commit_fee": "1085",
            "commit_weight": "600",
            "fee_per_kw": "1499",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },

```
Searching  in my logs the channel point:

```
2018-10-28 17:07:09.494 [INF] FNDG: Generated ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) for pendingID(674e9b30f92b902ecd4e3788d37618d57b5f0713f6d74ae916b
11ca3b4a3d7cb)
2018-10-28 17:07:10.754 [INF] FNDG: Broadcasting funding tx for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): (*wire.MsgTx)(0xc001194040)({
2018-10-28 17:07:10.765 [INF] LNWL: Inserting unconfirmed transaction 617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652
2018-10-28 17:07:11.221 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-28 17:07:11.222 [INF] CNCT: ChannelArbitrator(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): starting state=StateDefault
2018-10-28 17:07:11.233 [INF] NTFN: New spend subscription: utxo=617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0
2018-10-28 17:07:11.893 [INF] FNDG: Finalizing pendingID(674e9b30f92b902ecd4e3788d37618d57b5f0713f6d74ae916b11ca3b4a3d7cb) over ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cc
e6238993a4652:0), waiting for channel open on-chain
2018-10-28 17:07:11.895 [INF] NTFN: New confirmation subscription: txid=617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652, numconfs=3
2018-10-28 17:07:11.896 [INF] FNDG: Waiting for funding tx (617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652) to reach 3 confirmations
2018-10-28 17:07:11.893 [INF] CNCT: Close observer for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) active
2018-10-28 17:09:08.438 [WRN] FNDG: ChainNotifier shutting down, cannot complete funding flow for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-28 17:10:09.952 [INF] NTFN: New spend subscription: utxo=617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0
2018-10-28 17:10:09.956 [INF] CNCT: Close observer for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) active
2018-10-28 17:10:09.970 [INF] CNCT: ChannelArbitrator(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): starting state=StateDefault
2018-10-28 17:10:10.802 [INF] LNWL: Inserting unconfirmed transaction 617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652
2018-10-28 17:10:10.897 [INF] NTFN: New confirmation subscription: txid=617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652, numconfs=3
2018-10-28 17:10:10.898 [INF] FNDG: Waiting for funding tx (617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652) to reach 3 confirmations
2018-10-28 17:10:11.565 [INF] PEER: NodeKey(03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e) loading ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993
a4652:0)
2018-10-28 17:10:11.571 [WRN] PEER: Unable to find our forwarding policy for channel 617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0, using default values
2018-10-28 17:10:11.572 [INF] HSWC: ChannelLink(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) is starting
2018-10-28 17:10:11.573 [INF] HSWC: HTLC manager for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) started, bandwidth=988915000 mSAT
2018-10-28 17:10:11.574 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-28 17:10:11.577 [INF] HSWC: Received re-establishment message from remote side for channel(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
   PreviousOutPoint: (wire.OutPoint) 617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:1,
2018-10-28 17:31:00.720 [INF] LNWL: Marking unconfirmed transaction 617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652 mined in block 547707
2018-10-28 18:11:26.007 [INF] NTFN: Dispatching 3 conf notification for 617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652
2018-10-28 18:11:26.007 [INF] FNDG: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) is now active: ChannelID(52463a993862ce7c350f8d3a06fee1c73f9446e1391e34ca0a
140941a7387a61)
2018-10-28 18:11:26.156 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-28 18:11:27.266 [INF] CRTR: New channel discovered! Link connects 031d2bbc75802689312220a017c6b51fa246efc59c7aa9355f6f7395038ffb4d6a and 03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402
de65c6eb2e1be55dc3e with ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): chan_id=602210215139606528, capacity=0.01 BTC
2018-10-28 18:11:27.333 [INF] NTFN: New confirmation subscription: txid=617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652, numconfs=6
2018-10-28 18:54:33.436 [INF] NTFN: Dispatching 6 conf notification for 617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652
2018-10-28 18:54:33.438 [INF] FNDG: Announcing ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0), short_chan_id=(*lnwire.ShortChannelID)(0xc000622020)(547707:386
:0)
2018-10-28 19:16:15.802 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1270 sat/kw
2018-10-28 19:52:01.564 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1270 sat/kw
2018-10-28 20:41:33.208 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1270 sat/kw
2018-10-28 21:27:43.576 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1270 sat/kw
2018-10-28 22:12:55.593 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1271 sat/kw
2018-10-28 22:44:29.728 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1270 sat/kw
2018-10-28 23:03:09.411 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1270 sat/kw
2018-10-29 00:43:20.629 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1269 sat/kw
2018-10-29 01:25:19.568 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1269 sat/kw
2018-10-29 02:21:00.087 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1269 sat/kw
2018-10-29 03:14:42.365 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1269 sat/kw
2018-10-29 03:44:44.649 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1269 sat/kw
2018-10-29 04:10:17.831 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1004 sat/kw
2018-10-29 05:08:43.347 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1004 sat/kw
2018-10-29 05:29:09.486 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 1004 sat/kw
2018-10-29 06:01:39.330 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 902 sat/kw
2018-10-29 06:41:30.465 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 902 sat/kw
2018-10-29 07:12:01.828 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 880 sat/kw
2018-10-29 07:58:07.430 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 880 sat/kw
2018-10-29 08:39:38.896 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 877 sat/kw
2018-10-29 08:50:19.775 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 880 sat/kw
2018-10-29 09:12:51.426 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): updating commit fee to 877 sat/kw

```
I think this is relevant:
```
2018-10-28 18:11:26.007 [INF] FNDG: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) is now active: ChannelID(52463a993862ce7c350f8d3a06fee1c73f9446e1391e34ca0a
140941a7387a61)

```
but lncli doesn't show the channel as active.
Any ideas?

Thanks

### Your environment

lnd-0.5
linux
bitcoind-0.17

### Expected behaviour

The channels should be active

### Actual behaviour

The channel is not active

**Comment by halseth** [comment]
The peer is probably not online.

**Comment by danbadjar** [comment]
Hello, if I use lncli listpeers it seems to be online:
        {
            "pub_key": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
            "address": "52.15.79.245:9735",
            "bytes_sent": "4203204",
            "bytes_recv": "3286020",
            "sat_sent": "0",
            "sat_recv": "0",
            "inbound": false,
            "ping_time": "128583"
        },

**Comment by danbadjar** [comment]
Ok thanks. Rebooted in debug mode.

found this:

```
2018-10-29 11:27:52.545 [DBG] CNCT: New ChainEventSubscription(id=0) for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-29 11:27:52.549 [DBG] CNCT: Starting chain watcher for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-29 11:27:52.583 [INF] NTFN: New spend subscription: utxo=617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0
2018-10-29 11:27:52.618 [INF] CNCT: Close observer for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) active
2018-10-29 11:27:53.110 [DBG] CNCT: Starting ChannelArbitrator(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0), htlc_set=(contractcourt.htlcSet) {
2018-10-29 11:27:53.111 [INF] CNCT: ChannelArbitrator(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): starting state=StateDefault
2018-10-29 11:27:53.171 [DBG] CNCT: ChannelArbitrator(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): new block (height=547821) examining active HTLC's
2018-10-29 11:27:53.171 [DBG] CNCT: ChannelArbitrator(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): checking chain actions at height=547821
2018-10-29 11:27:54.841 [DBG] LNWL: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0), starting local commitment: (*lnwallet.commitment)(0xc0106f6000)({
    PreviousOutPoint: (wire.OutPoint) 617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0,
2018-10-29 11:27:54.874 [DBG] LNWL: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0), starting remote commitment: (*lnwallet.commitment)(0xc0106f6300)({
    PreviousOutPoint: (wire.OutPoint) 617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0,
2018-10-29 11:27:54.877 [INF] PEER: NodeKey(03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e) loading ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-29 11:27:54.902 [DBG] CNCT: New ChainEventSubscription(id=1) for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-29 11:27:54.918 [INF] HSWC: ChannelLink(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) is starting
2018-10-29 11:27:54.924 [INF] HSWC: HTLC manager for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) started, bandwidth=988915000 mSAT
2018-10-29 11:27:54.925 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-29 11:27:54.929 [DBG] SRVR: Announcing channel(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0) disabled=false
2018-10-29 11:27:54.924 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-29 11:27:54.935 [INF] HSWC: ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): resending FundingLocked message to peer
2018-10-29 11:27:54.940 [INF] HSWC: Received re-establishment message from remote side for channel(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-29 11:27:55.304 [INF] PEER: Already have ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0), ignoring.
2018-10-29 11:27:55.305 [INF] PEER: Processing retransmitted FundingLocked for ChannelPoint(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0)
2018-10-29 11:28:28.349 [DBG] CNCT: ChannelArbitrator(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): new block (height=547822) examining active HTLC's
2018-10-29 11:28:28.349 [DBG] CNCT: ChannelArbitrator(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): checking chain actions at height=547822
2018-10-29 11:29:42.037 [DBG] CNCT: ChannelArbitrator(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): new block (height=547823) examining active HTLC's
2018-10-29 11:29:42.038 [DBG] CNCT: ChannelArbitrator(617a38a74109140aca341e39e146943fc7e1fe063a8d0f357cce6238993a4652:0): checking chain actions at height=547823

```
And now the channel is active after almost 24 hours. 
Is this a bug?

**Comment by halseth** [comment]
From the logs you can see that the `FundingLocked` message was retransmitted, which allowed us to activate the channel.

It is hard to say what caused this, it could either be a bug on your side, or the remote's side. In any case, a reconnection fixed the problem, as the `fundingLocked` was retransmitted.

Without the full debug logs from when the channel was created, there's not more to be done. Please re-open if you have these logs, or if you encounter it again! 😀

**Comment by Roasbeef** [comment]
If the remote peer never sends `FundingLocked` (for w/e reason), then the channel won't be marked as active. That log from the funding manager is a bit misleading, as we print that when it's active from _our_ PoV, and even if the remote party hasn't yet sent the `FundingLocked` message.

**Comment by Roasbeef** [comment]
Also another item that can help, is getting a dump of the set of active goroutines. Using the `--profile` flag can help you obtain this.

**Comment by danbadjar** [comment]
Thanks for your help :)

**Comment by JoelFrutiger** [comment]
Just had this issue, restarting lnd helped send the FundingLocked. Maybe this message should be sent more than once.

**Comment by cfromknecht** [comment]
@JoelFrutiger let us know if you see this issue on any of the 0.6rc's. This should have beeen addressed by #2690 and #2902, but note that it probably requires both peers to have this update to fully resolve the issue

**Comment by JoelFrutiger** [comment]
Sorry for digging this up, you are correct, one of the peers was using version 0.5.0-beta

**Comment by danbadjar** [comment]
Still having problems with 0.5.2
Just upgraded to 0.6 rc3.
Let's see how it goes
