### ISSUE TITLE
panic: couldn't write cfheaders msg: attempt to write cfheaders out of order

### ISSUE THREAD

**Issue by rstmsn** [lightningnetwork/lnd#2174]
### Environment

* Version 0.5.0-beta commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d
* Darwin
* Neutrino

### Steps to reproduce

Createwallet -> Unlock -> Crash after reaching full block height on initial sync

```
2018-11-09 18:14:56.642 [INF] LNWL: Done catching up block hashes
2018-11-09 18:14:56.642 [INF] BTCN: Starting cfheaders sync for filter_type=0
2018-11-09 18:14:56.838 [INF] LNWL: Started rescan from block 000000000000008b758dcc23a118cb850f2bcd6e4edc266563b96c7f5357c7c2 (height 1382923) for 1 address
2018-11-09 18:14:56.986 [INF] BTCN: Fetching set of checkpointed cfheaders filters from height=0, hash=c0589c7f567cffaf7bc0c9f6ad61710b78d3c1afef5d65a2a08e8a753173aa54
2018-11-09 18:14:56.986 [INF] BTCN: Starting to query for cfheaders from checkpoint_interval=0
2018-11-09 18:14:58.234 [INF] BTCN: Attempting to query for 1442 cfheader batches
2018-11-09 18:14:58.660 [INF] BTCN: Verified 1 filter header in the last 37m4.04s (height 1, 2011-02-02 23:22:08 +0000 GMT)
panic: couldn't write cfheaders msg: attempt to write cfheaders out of order

goroutine 161 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders.func1(0x12616310, 0xbe9200, 0x125ac0f0, 0xbe90e0, 0x12486690, 0x501)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:871 +0x903
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*ChainService).queryBatch(0x12484c40, 0x12ed6000, 0x5a2, 0x5a2, 0x22f65f10, 0x1267e080, 0x0, 0x0, 0x0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/query.go:422 +0x86e
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders(0x124d0120, 0x12ece000, 0x5a2, 0x5a2, 0x125e40a8, 0x500)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:774 +0x709
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).cfHandler.func2(0x12882070, 0x124d0120, 0x160385, 0x12e9a060, 0xaafeb200, 0xae2c60)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:500 +0x30f
created by github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).cfHandler
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:440 +0x316`

```

Relaunching lnd produces the following repetitve warning:
```

2018-11-09 18:30:24.386 [INF] LTND: Version 0.5.0-beta commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d
2018-11-09 18:30:24.386 [INF] LTND: Active chain: Bitcoin (network=testnet)
2018-11-09 18:30:24.386 [INF] CHDB: Checking for schema update: latest_version=6, db_version=6
2018-11-09 18:30:24.426 [INF] RPCS: password RPC server listening on 192.168.0.4:10006
2018-11-09 18:30:24.426 [INF] RPCS: password gRPC proxy started at 192.168.0.4:8086
2018-11-09 18:30:24.426 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2018-11-09 18:30:36.512 [INF] LNWL: Opened wallet
2018-11-09 18:30:36.711 [INF] LTND: Primary chain is set to: bitcoin
2018-11-09 18:30:37.200 [INF] BTCN: Loaded 1001 addresses from file '/Users/rstmsn/Library/Application Support/Lnd/data/chain/bitcoin/testnet/peers.json'
2018-11-09 18:30:37.200 [INF] BTCN: Waiting for block headers to sync, then will start cfheaders sync...
2018-11-09 18:30:37.200 [INF] BTCN: Starting cfheaders sync at block_height=1442695, hash=00000000000000646b2c532067e840ed3294e1d84fe591a59630b894930e8a32
2018-11-09 18:30:37.200 [INF] BTCN: Starting cfheaders sync for filter_type=0
2018-11-09 18:30:37.200 [WRN] BTCN: Unable to fetch set of candidate checkpoints, trying again...
2018-11-09 18:30:37.303 [INF] CMGR: DNS discovery failed on seed testnet-seed.bitcoin.schildbach.de: lookup testnet-seed.bitcoin.schildbach.de on 192.168.0.1:53: no such host
2018-11-09 18:30:37.316 [INF] CMGR: 1 addresses found from DNS seed testnet-seed.bluematt.me
2018-11-09 18:30:37.337 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch on 192.168.0.1:53: no such host
2018-11-09 18:30:37.337 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org on 192.168.0.1:53: no such host
2018-11-09 18:30:37.477 [INF] BTCN: New valid peer 104.155.159.141:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
2018-11-09 18:30:37.588 [INF] BTCN: Syncing to block height 1442695 from peer 104.155.159.141:18333
2018-11-09 18:30:37.588 [INF] BTCN: Fetching set of headers from tip (height=1442695) from peer 104.155.159.141:18333
2018-11-09 18:30:38.754 [INF] LNWL: The wallet has been unlocked without a time limit
2018-11-09 18:30:38.754 [INF] LTND: LightningWallet opened
2018-11-09 18:30:38.827 [INF] LNWL: Started rescan from block 000000000000003faafeb24b33ebc7553bb061a163451cc1e7ff243e5410f14d (height 1442693) for 1 address
2018-11-09 18:30:38.828 [INF] HSWC: Restoring in-memory circuit state from disk
2018-11-09 18:30:38.829 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
2018-11-09 18:30:38.831 [INF] RPCS: RPC server listening on 192.168.0.4:10006
2018-11-09 18:30:38.831 [INF] LTND: Waiting for chain backend to finish sync, start_height=1442695
2018-11-09 18:30:38.831 [INF] RPCS: gRPC proxy started at 192.168.0.4:8086
2018-11-09 18:30:40.631 [WRN] BTCN: mismatch at height 1000, expected 8a116495a22639806b55c7fad5f9c6cd031cb41005e52a4afd516b5229e033ff got 20fdcc13d0563fac7b86e070d5e818a5f68974e4f35855e5937b1ca04e3b3522
2018-11-09 18:30:40.631 [WRN] BTCN: Detected mismatch at index=0 for checkpoints!!!
2018-11-09 18:30:41.024 [WRN] BTCN: mismatch at height 1000, expected 8a116495a22639806b55c7fad5f9c6cd031cb41005e52a4afd516b5229e033ff got 20fdcc13d0563fac7b86e070d5e818a5f68974e4f35855e5937b1ca04e3b3522
2018-11-09 18:30:46.648 [WRN] BTCN: mismatch at height 1000, expected 8a116495a22639806b55c7fad5f9c6cd031cb41005e52a4afd516b5229e033ff got 20fdcc13d0563fac7b86e070d5e818a5f68974e4f35855e5937b1ca04e3b3522
2018-11-09 18:30:46.648 [WRN] BTCN: Detected mismatch at index=0 for checkpoints!!!
2018-11-09 18:30:48.615 [WRN] BTCN: mismatch at height 1000, expected 8a116495a22639806b55c7fad5f9c6cd031cb41005e52a4afd516b5229e033ff got 20fdcc13d0563fac7b86e070d5e818a5f68974e4f35855e5937b1ca04e3b3522
2018-11-09 18:30:51.842 [WRN] BTCN: mismatch at height 1000, expected 8a116495a22639806b55c7fad5f9c6cd031cb41005e52a4afd516b5229e033ff got 20fdcc13d0563fac7b86e070d5e818a5f68974e4f35855e5937b1ca04e3b3522
2018-11-09 18:30:51.842 [WRN] BTCN: Detected mismatch at index=0 for checkpoints!!!

```

**Comment by halseth** [comment]
This is fixed in the upcoming v0.5.1 release :)

**Comment by kiwiidb** [comment]
I am still getting this error while neutrino is syncing and attempting to unlock the wallet:
lnd.conf:
```
bitcoin.mainnet=1
bitcoin.active=1
bitcoin.node=neutrino
```

Logs:
```
Nov 13 11:24:23 P2P lnd[28698]: 2019-11-13 11:24:23.623 [INF] BTCN: Processed 2000 blocks in the last 18.33s (height 318256, 2014-08-30 16:10:28 +0200 CEST)
Nov 13 11:24:23 P2P lnd[28698]: 2019-11-13 11:24:23.688 [INF] BTCN: Verified 2000 filter headers in the last 18.39s (height 310001, 2014-07-10 01:18:12 +0200 CEST)
Nov 13 11:24:23 P2P lnd[28698]: 2019-11-13 11:24:23.780 [INF] BTCN: Verified downloaded block header against checkpoint at height 319400/hash 000000000000000021c6052e9becade189495d1c539aa37c58917305fd15f13b
Nov 13 11:24:38 P2P lnd[28698]: 2019-11-13 11:24:38.489 [INF] BTCN: Processed 1145 blocks in the last 14.86s (height 319401, 2014-09-06 16:52:35 +0200 CEST)
Nov 13 11:24:38 P2P lnd[28698]: 2019-11-13 11:24:38.522 [INF] BTCN: Verified 4000 filter headers in the last 14.83s (height 314001, 2014-08-05 01:02:28 +0200 CEST)
Nov 13 11:24:38 P2P lnd[28698]: panic: couldn't write cfheaders msg: attempt to write cfheaders out of order! Tip=5012c16a5674d0485b09cfb101657f7633ef372a2e1e3df66929c62254fe6e22 (height=316000), prev_hash=13eeed9f0f6ff2bc8b4badbab152da3fa38fec93314068a281cefd164f59fbc9
```
LND version `0.8.0-beta`

The panic occurs just after doing the `lncli unlock`.

As I was trying to do it again, by the 3rd time I was unlocking the wallet the crash no longer happened...

**Comment by halseth** [comment]
@kiwiidb Do you see this on master also?

**Comment by kiwiidb** [comment]
The issue took place on a resource-constrained device (raspberry pi), which has now fully synced using neutrino. I have been unable to reproduce it both on master or on `0.8.0` on my own laptop which syncs the headers much faster.

**Comment by wpaulino** [comment]
> The issue took place on a resource-constrained device (raspberry pi), which has now fully synced using neutrino. I have been unable to reproduce it both on master or on 0.8.0 on my own laptop which syncs the headers much faster.

@kiwiidb could you retry the sync multiple times with both `v0.8.0` and `master` on the raspberry pi? This should no longer be an issue on the master branch.

**Comment by halseth** [comment]
This should also be fixed in the `v0.8.1` release as well as master. Please reopen if you see it on either!
