### ISSUE TITLE
Private ChannelUpdate is not sent after funding gets 4 confirmations

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#2907]
Users were complaining about not being able to receive so I've tried to open two channels to LND `0.5.2-99-beta commit=queue/v1.0.1-269-gfa73a60167aa07df948020eb5f1f31893a113f9c`, here are my findings:

For the first channel BLW was kept online, remote peer started sending a private `ChannelUpdate` on reconnection once funding got its first confirmation (is it not too soon by the way?) and stopped doing that once funding had 4 confirmations.

For the second channel I closed BLW once funding was published and opened it when it had 10 confirmations, no `ChannelUpdate` was sent at all. If this is how it is supposed to work it's hardly a good fix for https://github.com/lightningnetwork/lnd/issues/1347 as mobile users often don't keep their devices online for a long time.

**Comment by btcontract** [comment]
Also want to note that Eclair just sends a private `ChannelUpdate` on each reconnection, forever. Traffic overhead is marginal but receiving ability is ensured, can't LND do the same?

**Comment by cfromknecht** [comment]
@btcontract do you notice the same behavior with 0.6rc3? AFAIK 0.5.X releases do not include the fix for #1347

**Comment by halseth** [comment]
Commit `fa73a60167aa07df948020eb5f1f31893a113f9c` should have  the fix for #1347

**Comment by LNBIG-COM** [comment]
Right now i updated all servers to commit 1fea5b09b28fa6cb0b4a70e597a160449a55aaeb (master branch today)
For already opened channel there are nothing changes (no channel updates messages as told to me @btcontract )
And now i and @btcontract were testing new opened channels on BLW from LND. Now the mempool is very high loaded. New channels opened from LND to be made with 10 sat/byte so only tomorrow we will see. But my opinion - the bug is there...

**Comment by btcontract** [comment]
Behavior is the same 0.6rc3. Neither old nor newly opened channel gets an update.

**Comment by wpaulino** [comment]
The `ChannelUpdate` should be sent upon reconnection every time regardless of whether it has confirmed or not as long as it remains private. @LNBIG-COM could you bump up `DISC` logs to debug and post what you see here?

**Comment by LNBIG-COM** [comment]
https://drive.google.com/open?id=1NHrnYQsSiCXNxxEpr_kj9uU8KwexYXy9

I turned on DISC to debug but i didn't find usefull info
After i turned on trace level for all and tried to connect to lnd-05 from BLW
Here small crypted log of all events for this small period
The file was encrypted for key `4096R/1F98A67C 2018-03-06 "Conner Fromknecht <conner@lightning.engineering>"`

My BLW node id is `02db9eb1e37acbdc9a987eaf878bd3c3d5f5c9afa2159310e048d816f344d29358`

**Comment by LNBIG-COM** [comment]
I think you can debug yourself
Go to lnbig.com -> choose type channel for LND/Eclair nodes for example -> choose Private on switch -> create channel to your node
After turn off internet (!!!) in your node and to wait for example 10 confirmations of funding transaction. After turn on internet again and to see messages in channel. You will not see ChannelUpdate messages... You should not have internet in your node between time from zero to 6-10 confirmations for clean experiment. If you will have the internet you will not see the bug.

**Comment by wpaulino** [comment]
Do you see the private channel in the output of `lncli describegraph --include_announced`?

I've tested the resending of `ChannelUpdate`s logic between two lnd nodes within multiple different connection scenarios and haven't been able to reproduce the issue.

**Comment by btcontract** [comment]
When logging all incoming messages from remote LND, this is what I get:

```
<-- Init(ByteVector(empty),ByteVector(1 bytes, 0x81))
<-- ChannelReestablish(ByteVector(32 bytes, 0xd3ad1ffd448cfed14d65e7b9e5fa66b2557582fbe0dc921068fb51163f8cb210),1,0,Some(0000000000000000000000000000000000000000000000000000000000000000),Some(036eb015d2c331f99e3aadb21ee93a8c2ed89fabfe01a9fda5fd6d24f2744b6993))
<-- FundingLocked(ByteVector(32 bytes, 0xd3ad1ffd448cfed14d65e7b9e5fa66b2557582fbe0dc921068fb51163f8cb210),03c8590b3d97f125da69f630582ce6c14e92a3f9ad15d73c119b896317873a42ea)
<-- Pong(ByteVector(4 bytes, 0x00000000))
<-- Pong(ByteVector(11 bytes, 0x0000000000000000000000))
<-- Pong(ByteVector(15 bytes, 0x000000000000000000000000000000))
<-- Ping(16,ByteVector(empty))
<-- ChannelUpdate(ByteVector(72 bytes, 0x3045022100aed81dd2cf7651c9b7dcca2b79de202a0dc0edde9613f8fb55c16dd056ad400f02203d9cfde60c21c6a76cebd7bcfc6da6933bc4edccdb161510ee1af428e522a57601),ByteVector(32 bytes, 0x6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000),623226280428109824,1554787278,1,1,30,1000,0,2,Some(2970000000))
<-- ChannelUpdate(ByteVector(71 bytes, 0x3044022010e482f9f8866ec929a73ec699ed19b1b36638aefdb056d8c72029c195933ed3022048b1049776205601fe41504960edb80026a225634c6007cb6dbeb55132efd09901),ByteVector(32 bytes, 0x6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000),620539074053079040,1554787362,1,0,144,1000,1000,1,Some(97265000))
<-- ChannelUpdate(ByteVector(72 bytes, 0x3045022100f778120a7de0ea0effa92269fb041b1c77895330e11ed1dbfd5b69c7c6eef4c20220160ec6849b5a0d7dbb483250ecd8e7d2724930676109db2d9b978bed0499b9e301),ByteVector(32 bytes, 0x6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000),608210250141663233,1554787280,1,2,142,1000,2000,492,Some(3000000000))
<-- ChannelUpdate(ByteVector(72 bytes, 0x3045022100cad25c588c2655e6f1ed2a477c9091f7ef68cf56f3c1cebf6a73d38dce98dc7502205b5ef8d2ed266f469d93b5fad8b81d97a873ab14c3e36be7774a599c87a15f8301),ByteVector(32 bytes, 0x6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000),613598956622053377,1554787302,0,1,144,1000,1000,1,None)
<more gossip, no ChannelUpdate with local channel short id>
```

**Comment by btcontract** [comment]
Could it be related to `local-features`? BLW sends "02" (no initial routing sync, no channel range queries).

**Comment by wpaulino** [comment]
> Could it be related to local-features? BLW sends "02" (no initial routing sync, no channel range queries).

`lnd` should be sending it regardless.

**Comment by LNBIG-COM** [comment]
> Do you see the private channel in the output of `lncli describegraph --include_unannounced`?
> 
> I've tested the resending of `ChannelUpdate`s logic between two lnd nodes within multiple different connection scenarios and haven't been able to reproduce the issue.

Yes

    {
        "last_update": 0,
        "pub_key": "02db9eb1e37acbdc9a987eaf878bd3c3d5f5c9afa2159310e048d816f344d29358",
        "alias": "",
        "addresses": [
        ],
        "color": "#000000"
    },

    
    ...
    
    
    {
        "channel_id": "627579246951792640",
        "chan_point": "e315301024a6f963f7855f3c3c97dd631cd3fa01e1678a5b18f1125fe4585363:0",
        "last_update": 1554748140,
        "node1_pub": "02db9eb1e37acbdc9a987eaf878bd3c3d5f5c9afa2159310e048d816f344d29358",
        "node2_pub": "031ce29116eab7edd66148f5169f1fb658fad62bdc5091221ab895fe5d36db00b2",
        "capacity": "2860000",
        "node1_policy": null,
        "node2_policy": {
            "time_lock_delta": 30,
            "min_htlc": "1000",
            "fee_base_msat": "0",
            "fee_rate_milli_msat": "800",
            "disabled": false,
            "max_htlc_msat": "2860000000"
        }
    },

**Comment by LNBIG-COM** [comment]
> Do you see the private channel in the output of `lncli describegraph --include_unannounced`?
> 
> I've tested the resending of `ChannelUpdate`s logic between two lnd nodes within multiple different connection scenarios and haven't been able to reproduce the issue.

Did you try what i suggest for test above? (here: https://github.com/lightningnetwork/lnd/issues/2907#issuecomment-481037011)
I think if you will do you will see

**Comment by LNBIG-COM** [comment]
@wpaulino , you asked me logs
I did it. Did you see theirs? I logged there maximum info (trace level)

**Comment by wpaulino** [comment]
The issue stems from the not correctly handling the behavior when a private channel's policy is being updated manually on the `lnd` side. Thanks for the report, it'll either be addressed in https://github.com/lightningnetwork/lnd/pull/2917 or as a separate PR.

**Comment by btcontract** [comment]
Should a fix work for already existing channels or does it only apply to fresh ones? My currently existing channel still does not get an update on reconnect with updated LND.

**Comment by LNBIG-COM** [comment]
Today i upgrades all LNDs up to `0.6.0-beta commit=v0.6-beta-rc4-4-g2b43da422093c077fd27270f0bc0f3d1ad4c166c` . It's today master branch.

After i told to @btcontract that servers are upgraded.

Then i checked myself BLW wallets and i didn't see warning that an inbound opened channel is not ready for receiving (this warning is when the BLW doesn't know fee for channels because it didn't get updates after 4 and more confirmations). But right now i known that this warning was removed from current BLW version. So bug may be there or not yet. I am not sure already now...

I can only rely on conclusions of @btcontract because he can see full debug info in channels.

**Comment by wpaulino** [comment]
@btcontract a new update will need to be created for the channel on lnd's side.

**Comment by btcontract** [comment]
Can confirm updates now work for existing channels as well as for fresh ones, thanks for the fix.
