### ISSUE TITLE
lnwallet: incorrect dust limit applied for p2wkh outputs

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#3946]
### Background

Cannot use `sendcoins` to send 294 sats to a p2wkh address.

### Your environment

* lnd v0.9.0-beta-rc3
* linux
* btcd 0.20.0-beta

### Steps to reproduce

* `lncli newaddress p2wkh`
* `lncli sendcoins <address_from_above> 294`

### Expected behaviour

Coins sent

### Actual behaviour

[lncli] rpc error: code = Unknown desc = transaction output is dust

**Comment by Roasbeef** [comment]
So we use the P2WSH value rather than p2wkh: https://github.com/lightningnetwork/lnd/blob/8b04cfbf12f460853e8c55611cd1bba21b1510ef/lnwallet/parameters.go#L12

**Comment by Roasbeef** [comment]
Fix for 0.11?

**Comment by MrManPew** [comment]
@Xekyo maybe you can double check this one?
Thanks

**Comment by cfromknecht** [comment]
@joostjager should we keep this on the 0.11 target?

**Comment by joostjager** [comment]
To me it seems this isn't on the list of most pressing issues, I just wanted to report it. I am ok with removing from 0.11

**Comment by Xekyo** [comment]
> @Xekyo maybe you can double check this one?
> Thanks

@MrManPew:
A p2wpkh input should have up to 68 vbytes and a p2wpkh output has 31 bytes, so by using the same dust definition as Bitcoin Core, the dust limit for p2wpkh would be `(68+31)×3 = 297`. That may be why 294 is failing?

**Comment by halseth** [comment]
As pointed out by @cfromknecht this is also not correct for Litecoin: https://github.com/lightningnetwork/lnd/blob/0cba47dac04d663db81016bdf1cd7bc28a23841b/sweep/tx_input_set.go#L125

**Comment by Xekyo** [comment]
@MrManPew: I was just looking at this notification and another project that was also investigating an input size related issue, so I wrote https://bitcoin.stackexchange.com/q/100159/5406

**Comment by Roasbeef** [comment]
IIRC @wpaulino  this was fixed recently in `btcwallet` when resolving the issue w/ change addrs from mixed scopes?

**Comment by wpaulino** [comment]
No, those changes were unrelated. The issue is still present.

**Comment by Crypt-iQ** [comment]
> > @Xekyo maybe you can double check this one?
> > Thanks
> 
> @MrManPew:
> A p2wpkh input should have up to 68 vbytes and a p2wpkh output has 31 bytes, so by using the same dust definition as Bitcoin Core, the dust limit for p2wpkh would be `(68+31)×3 = 297`. That may be why 294 is failing?

@Xekyo
From my calculations a dust limit for p2wpkh is 294 sats as bitcoin core calculates an input with 67 and an output with 31. I was also looking at this answer and noticed you said 546 or less when it should be 545 or less as 546 is valid and standard.

**Comment by Xekyo** [comment]
Hi Crypt-iQ, I don't think that 67 is correct. Could you elaborate how you arrived at this value? As posted above, I explained how I arrive at the vsize of 67.75 vB or 68 vB for P2WPKH inputs here: https://bitcoin.stackexchange.com/q/100159/5406. This seems consistent with the vsize of a random P2WPKH tx I just looked up on a blockexplorer on mainnet.

**Comment by Crypt-iQ** [comment]
Hi @Xekyo, according to [this](https://github.com/bitcoin/bitcoin/blob/94f83534e4b771944af7d9ed0f40746f392eb75e/src/policy/policy.cpp#L40) bitcoin core should calculate 67 vbytes due to a rounding down since 107/4 = 26 in cpp rather than 26.75.  This would give 67 vbytes for an input instead of 67.75 or 68.

**Comment by Xekyo** [comment]
Args. :face_with_head_bandage:

Well, as you noted, the actual size of a P2WPKH input is 67.75 vB or 68 vB, depending on whether you get a low-r or high-r signature. But apparently, when the dust limit was implemented for p2wpkh, the author didn't round up as is policy for the conversion of weight to vsize.
I would expect that Bitcoin Core will continue to use this value for the dust limit as changing it would affect network policy interactions. I would suspect, though, that this error only applies to the dust calculation, and the correct weight is relevant in other places e.g. for the `minRelayTxFeeRate`.

**Comment by Crypt-iQ** [comment]
I will have to check bitcoin core's relay dust in a functional/unit test, but I suspect it's the same as btcd's (which pulled the relevant code from Core) and counts 294 as lowest non-dust for p2wpkh.  Your calculations *are* correct, just the code is wrong.  Also, do you happen to know why the output being spent's serialized size is included in the calculation for dust?  I ask because the output serialized size isn't included in the spending transaction, so I'm not sure why it's counted?

**Comment by Xekyo** [comment]
In the case of change, you would have some amount of leftover, and you'd be facing the decision whether to create a change output in the first place, so you'd face the future cost of the output size and the input size. In the case of recipient outputs, the costs are split between the sender and the receiver, but you still need to pay for both to create and spend the dust output.

**Comment by Crypt-iQ** [comment]
So if I understand correctly, it's trying to calculate the future cost of spending it, which assumes that it spends to the same output size? But if we take 330 sats as P2WSH dust, that cannot be spent to another P2WSH output (when taking into account fees) unless combined with another input since 330 - fees < 330

**Comment by Shymaa-Arafat** [comment]
I think this paper maybe helpful to ur work
https://royalsocietypublishing.org/doi/10.1098/rsos.180817
In this table, u'll find the min size of P2WSH to be 68 byte as u stated in ur work
https://royalsocietypublishing.org/doi/10.1098/rsos.180817#RSOS180817TB3
They defined 2 parameters little different than that of Bitcoin Core; a lower bound & an estimated value.
But how do u estimate the Satoshi/byte fee?
In their analysis, they make it a variable parameter and draw some curves for it. Here do u calculate it from the market as a running variable, or just have an estimate for it?
.
I'm interested in the number/ratio of dust UTXOS ( to measure the benefit from storing their hashes {or maybe them in a latter stage} in a separate Merkle Tree), do u calculate that in ur code?

Thank u

**Comment by Shymaa-Arafat** [comment]
I think this paper maybe helpful to ur work
https://royalsocietypublishing.org/doi/10.1098/rsos.180817
In this table, u'll find the min size of P2WSH to be 68 byte as u stated in ur work
![IMG_20210805_214546](https://user-images.githubusercontent.com/83260375/128411705-a22f2859-d027-4079-941e-5e9f8c0cf17a.jpg)

They defined 2 parameters little different than that of Bitcoin Core; a lower bound & an estimated value.
But how do u estimate the Satoshi/byte fee?
In their analysis, they make it a variable parameter and draw some curves for it. Here do u calculate it from the market as a running variable, or just have an estimate for it?
.
I'm interested in the number/ratio of dust UTXOS ( to measure the benefit from storing their hashes {or maybe them in a latter stage} in a separate Merkle Tree), do u calculate that in ur code?

Thank u

**Comment by Xekyo** [comment]
> So if I understand correctly, it's trying to calculate the future cost of spending it, which assumes that it spends to the same output size? But if we take 330 sats as P2WSH dust, that cannot be spent to another P2WSH output (when taking into account fees) unless combined with another input since 330 - fees < 330

TBH, now that you ask like that, it's not quite clear to me why the output cost is added. If the potential dust output were to become one of multiple inputs, the added cost of an output seems like an overestimate of the future transaction cost pertaining to the newly created UTXO. OTOH, if the assumption were that the potential dust output must pay for a whole 1-input-1-output transaction, it's underestimating the cost by not accounting for the transaction header (and a potentially larger output size).

It doesn't even make sense if you'd consider the "dust value" to be the cut-off for leftover amounts _before_ creating the output, because the cost of creating change would be dependent on the current feerate rather than the discard_feerate. Possibly, somebody just implemented _something_ at that time, but they hadn't thought it through all the way to the end.

If I were to start from scratch, I'd probably use the current `feerate×output weight + input weight×discard_feerate` as the limit for when to drop funds to the change, but `input weight×discard_feerate` as the cut-off for foreign transactions' outputs to be dust.

**Comment by Shymaa-Arafat** [comment]
I think if the default coin strategy were to select the smallest UTXO u have, say "a" (if u have dust) & the smaller  non-dust UTXO, say "A", such that
(A+a) - X > dust_threshold
(X is the amount u want to pay)
This way:
1-u spend ur dust with a small cost of only 1added UTXO instead of a complete TX (as he just said in the previous comment)
2-u avoid creating more dust
