### ISSUE TITLE
22 channels were force closed, txid available but haven't arrived according to lncli. 

### ISSUE THREAD

**Issue by kaspar-nl** [lightningnetwork/lnd#4028]
### Background
Some of my channels were 'force closed' about a week ago, and still don't have received my funds. I am new to the LND space, and enjoy the super fast speeds of tx so far! I am trying out some more stuff, but I am stuck now with this issue, that I hope can be solved with your help!

### My environment
* lncli version 0.9.0-beta commit=v0.9.0-beta-90-g2c08a8b9a89839936531dedd4b1459153da64229
* Bitcoin Core RPC client version v0.19.0.1
* Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux  (accessible on clearnet via SSH tunnel via another public IP, Port 9735).

### My steps to reproduce
* Some of my channels were closed: 1) maybe because I started autopilot?; 2) maybe because the server was temporarily not available on the (clear)net?

### Expected behaviour
As far as I understand, when a channel is **force closed** it should appear after the 'block_til_maturity' on your balance/wallet, and should be visible with the **walletbalance**. 

### Actual behaviour
* lncli pendingchannels shows 22 "pending_force_closing_channels". Each has a unique "closing_txid" (as expect). **maturity_heights** and **blocks_til_maturity** are all "0". 
* When I look up the **txid** in the lnd.log file I see: e.g. `[ERR] CNCT: ChannelArbitrator(fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff:0): unable to progress *contractcourt.commitSweepResolver: **cannot get confirmation for commit tx** f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af` 

I feel that the solution of this issue lies in the **cannot get confirmation for commit tx** info, but have no idea how to fix it (also not after some search @Github). I hope you can help me! Right now issue is not so big, but imagine that you have 100.000.000 Sats in 'limbo'  and you have no idea when they arrive.  Should I start my bitcoind with -txindex?

I also ran a 'Forced In-Place Rescan' (https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan), and after starting the lnd, and check the logs, I found:

```
2020-02-22 10:30:22.817 [INF] NTFN: **New confirmation subscription:** conf_id=8, txid=f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af, num_confs=1 height_hint=617158
2020-02-22 11:10:39.799 [INF] NTFN: **Dispatching 1 confirmation notification for** txid=f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af
2020-02-22 11:10:39.799 [INF] NTFN: **Canceling confirmation notification: conf_id=8, txid**=f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af
2020-02-22 11:10:39.800 [INF] SWPR: **Sweep request received: out_point**=f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af:0, witness_type=CommitmentNoDelayTweakless, time_lock=0, amount=0.0001488 BTC, fee_preference=6 blocks, force=false
2020-02-22 11:10:40.615 [INF] NTFN: **New spend subscription: spend_id=42, outpoint**=f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af:0, script=0 e6b52c77307476a11bbe251703a9624e7de7480d, height_hint=617159
2020-02-22 11:10:40.615 [INF] NTFN: **Dispatching historical spend rescan for outpoint**=f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af:0, script=0 e6b52c77307476a11bbe251703a9624e7de7480d, start=617159, end=618498
   PreviousOutPoint: (wire.OutPoint) f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af:0,
   PreviousOutPoint: (wire.OutPoint) f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af:0,
2020-02-22 11:45:22.285 [INF] NTFN: **Canceling spend notification: spend_id=42, outpoint**=f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af:0, script=0 e6b52c77307476a11bbe251703a9624e7de7480d
2020-02-22 11:45:24.415 [INF] NTFN: **Historical spend dispatch finished for request outpoint**=f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af:0, script=0 e6b52c77307476a11bbe251703a9624e7de7480d (start=617159 end=618498) with details: 872bd1f556229c2f5e27167511a09730d4e45232b5bc2b5d2c206f64fff40409[3] spending f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af:0 at height=617159`
```

Example of a force closed channel:
```
{
            "channel": {
                "remote_node_pub": "02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c",
                "channel_point": "fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff:0",
                "capacity": "20000",
                "local_balance": "14880",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0"
            },
            "closing_txid": "f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af",
            "limbo_balance": "14880",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }
```

**Comment by toptim** [comment]
the same with one force close inactive channel
`
lncli closechannel ac3a1f375fa10d28940acaeb056cc0461b266c3235e8dbd9b8881d85e659ffea
"closing_txid": "dd0173210f700393f764d9a38c1bef2dfd52eac9051fe97de04024ad61740789"
[INF] CNCT: ChannelArbitrator(ac3a1f375fa10d28940acaeb056cc0461b266c3235e8dbd9b8881d85e659ffea:0): starting state=StateWaitingFullResolution
[DBG] CNCT: ChannelArbitrator(fff572c88b78cfec6ecf38b9c4d83679add4040288fc584775c67c01abc1cdf1:0): new block (height=618772) examining active HTLC's
[DBG] CNCT: ChannelArbitrator(fff572c88b78cfec6ecf38b9c4d83679add4040288fc584775c67c01abc1cdf1:0): checking commit chain actions at height=618772, in_htlc_count=0, out_htlc_count=0
[INF] CNCT: ChannelArbitrator(ac3a1f375fa10d28940acaeb056cc0461b266c3235e8dbd9b8881d85e659ffea:0): still awaiting contract resolution
[INF] CNCT: ChannelArbitrator(ac3a1f375fa10d28940acaeb056cc0461b266c3235e8dbd9b8881d85e659ffea:0): relaunching 1 contract resolvers
[INF] DISC: Authenticated Gossiper is starting
[DBG] CNCT: ChannelArbitrator(ac3a1f375fa10d28940acaeb056cc0461b266c3235e8dbd9b8881d85e659ffea:0): attempting to resolve *contractcourt.commitSweepResolver
[DBG] CNCT: ChannelArbitrator(ac3a1f375fa10d28940acaeb056cc0461b266c3235e8dbd9b8881d85e659ffea:0): contract *contractcourt.commitSweepResolver not yet resolved
[INF] NTFN: New confirmation subscription: conf_id=1, txid=dd0173210f700393f764d9a38c1bef2dfd52eac9051fe97de04024ad61740789, num_confs=1 height_hint=618755
[DBG] NTFN: Dispatching historical confirmation rescan for txid=dd0173210f700393f764d9a38c1bef2dfd52eac9051fe97de04024ad61740789
[INF] BRAR: Starting contract observer, watching for breaches.
[INF] NTFN: New block epoch subscription
[DBG] DISC: Requesting online notification for peer=020c27b1e99dce7b952757be0b0d7c42ab825270c4f8f7571a349624da408b2dc8
[DBG] DISC: Requesting online notification for peer=03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f
[DBG] DISC: Requesting online notification for peer=03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d
[DBG] DISC: Requesting online notification for peer=0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4
[DBG] DISC: Requesting online notification for peer=03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e
[DBG] DISC: Requesting online notification for peer=0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c
[DBG] DISC: Requesting online notification for peer=0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3
[DBG] DISC: Requesting online notification for peer=037f990e61acee8a7697966afd29dd88f3b1f8a7b14d625c4f8742bd952003a590
[DBG] DISC: Requesting online notification for peer=0395033b252c6f40e3756984162d68174e2bd8060a129c0d3462a9370471c6d28f
[DBG] DISC: Requesting online notification for peer=0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266
[INF] CRTR: FilteredChainView starting
[DBG] NTFN: Updating confirmation details for txid=dd0173210f700393f764d9a38c1bef2dfd52eac9051fe97de04024ad61740789
[INF] NTFN: Dispatching 1 confirmation notification for txid=dd0173210f700393f764d9a38c1bef2dfd52eac9051fe97de04024ad61740789
[INF] NTFN: Canceling confirmation notification: conf_id=1, txid=dd0173210f700393f764d9a38c1bef2dfd52eac9051fe97de04024ad61740789
[DBG] CNCT: *contractcourt.commitSweepResolver(ac3a1f375fa10d28940acaeb056cc0461b266c3235e8dbd9b8881d85e659ffea:0): commit conf_height=618755, unlock_height=618899
[DBG] CNCT: *contractcourt.commitSweepResolver(ac3a1f375fa10d28940acaeb056cc0461b266c3235e8dbd9b8881d85e659ffea:0): waiting for csv lock to expire at height 618899
[INF] NTFN: New block epoch subscription
[INF] CRTR: Filtering chain using 36453 channels active
[INF] CRTR: Prune tip for Channel Graph: height=618772, hash=000000000000000000064ee5d77797639180328c805acc5f33c093a1c504f5c3
[DBG] INVC: Adding %!v(MISSING) pending invoices to the expiry watcher
`
must wait 618899 block to unlock?

**Comment by wpaulino** [comment]
> As far as I understand, when a channel is force closed it should appear after the 'block_til_maturity' on your balance/wallet, and should be visible with the walletbalance.

After `blocks_til_maturity` is when you're able to sweep the output, but it doesn't necessarily mean that the process has completed yet. Are those channels still found in `lncli pendingchannels`, or are they in `lncli closedchannels` now?

> [DBG] CNCT: *contractcourt.commitSweepResolver(ac3a1f375fa10d28940acaeb056cc0461b266c3235e8dbd9b8881d85e659ffea:0): waiting for csv lock to expire at height 618899

You force closed this channel, so you need to wait for the time lock to expire. This was done to give time to your channel counterparty to present evidence to the chain (if necessary) that you've attempted to settle an invalid state.

**Comment by kaspar-nl** [comment]
@wpaulino thanks for your reply! It does make sense that the sats in the locked address doesn't go automatically to your BTC-adress, and that you need to 'sweep' it. 

I checked today again and funds are still in my 22 channels, and cannot have access to it. I checked the log files and I see:

 `2020-02-24 14:10:47.194 [INF] NTFN: Historical spend dispatch finished for request outpoint=f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af:0, script=0 e6b52c77307476a11bbe251703a9624e7de7480d (start=617159 end=618789) with details: 872bd1f556229c2f5e27167511a09730d4e45232b5bc2b5d2c206f64fff40409[3] spending f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af:0 at height=617159`

and checking the pending channel I see 22: pending_force_closing_channels:
`{
            "channel": {
                "remote_node_pub": "02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c",
                "channel_point": "fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff:0",
                "capacity": "20000",
                "local_balance": "14880",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0"
            },
            "closing_txid": "f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37eca25124c45af",
            "limbo_balance": "14880",
            "maturity_height": 617158,
            "blocks_til_maturity": -1711,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }`

How can I 'release' the funds, so they come back to my BTC-address (onchain)?

**Comment by Roasbeef** [comment]
>                 "local_balance": "14880",

It may be the case that the on-chain fees are prohibitive at this current level for sweeping. We _do_ now have a "force sweep" mode, but that isn't yet hooked in for regular sweeps like this.

**Comment by wpaulino** [comment]
@kaspar-nl any updates? Looking at the channel `fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff`, it seems to have been resolved on-chain already.

**Comment by kaspar-nl** [comment]
Dear @wpaulino,

Thanks for your message, and I checked again and still see the 22 "pending_force_closing_channels" such as this one:

`            "channel": {
                "remote_node_pub": "02004c625d622245606a1ea2c1c69cfb4516b703b479                         45a3647713c05fe4aaeb1c",
                "channel_point": "fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e8                         59db5658678f69b8ff:0",
                "capacity": "20000",
                "local_balance": "14880",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0"
            },
            "closing_txid": "f176457612166c3bcaad566d78b4fa6df5f29d5740415655b37                         eca25124c45af",
            "limbo_balance": "14880",
            "maturity_height": 617158,
            "blocks_til_maturity": -2916,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }
`

**Comment by wpaulino** [comment]
Could you filter for `CNCT` logs of some of your channels in this state and paste them here?

**Comment by kaspar-nl** [comment]
Please find below a selection of the `CNCT ` logs:

```
2020-03-04 02:20:39.966 [INF] CNCT: ChannelArbitrator(fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff:0): starting state=StateWaitingFullResolution
2020-03-04 02:20:41.307 [INF] CNCT: ChannelArbitrator(fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff:0): still awaiting contract resolution
2020-03-04 02:20:41.308 [INF] CNCT: ChannelArbitrator(fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff:0): relaunching 1 contract resolvers
2020-03-04 03:59:52.926 [INF] CNCT: *contractcourt.commitSweepResolver(fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff:0): sweeping commit output
2020-03-04 05:26:46.612 [ERR] CNCT: *contractcourt.commitSweepResolver(fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff:0): unable to sweep input: remote party swept utxo
2020-03-04 05:26:46.612 [ERR] CNCT: ChannelArbitrator(fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff:0): unable to progress *contractcourt.commitSweepResolver: remote party swept utxo
```

**Comment by wpaulino** [comment]
Have you performed any recovery attempts with your `channel.backup`?

**Comment by kaspar-nl** [comment]
@wpaulino, thank you for your idea, and hereby I confirm that I have NOT yet done any recovery attempts, as I though it is better to ask here before starting a recovery procedure for my issue. 

Do you think I should perform any recovery attempts? If so, please let me know which procedure is the best in my case!

I really hope we can fix this issue, so when other people have this issue, they know exactly how to deal with it!

**Comment by wpaulino** [comment]
Recovery won't be necessary. The issue you're having now is that `lnd` is trying to sweep the output back to a wallet address, but it can't do so because it's already been spent, possibly because it already swept it and there's a bug somewhere. Is the transaction `872bd1f556229c2f5e27167511a09730d4e45232b5bc2b5d2c206f64fff40409` relevant to you, i.e., do you see it in `lncli listchaintxns`?

**Comment by kaspar-nl** [comment]
I see the following tx:
``
{                                                                                                                                                                                                          "tx_hash": "872bd1f556229c2f5e27167511a09730d4e45232b5bc2b5d2c206f64fff40409",
            "amount": "47002",
            "num_confirmations": 4148,
            "block_hash": "00000000000000000000d9898c679026cf5b6ca200923d055a6addda37faa2f5",
            "block_height": 617159,                                                                                                                                                                                "time_stamp": "1581569351",
            "total_fees": "0",                                                                                                                                                                                     "dest_addresses": [
                "bc1qqj4e0vvx6pnaapkpmlh6egygjpr5gn2xj89dw3"
            ],                                                                                                                                                                                                     "raw_tx_hex": "02000000000106f2766a37172887a9ab016e4bfe073366d6bde0ebfd23075caf573ef00f89d729000000000000000000ffb0e5d69c47aa7974899c83673eb480a935011561abc151965436c10d3fb16601000000000$        }
``

**Comment by wpaulino** [comment]
That would mean you already swept the channel `fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff`, since the funds ended up being used for the channel `0905e3ae14f01abb49f4568ec7376a50b96e4147fb62581a3280a546459aebe6`. This is likely the case for your other force closing channels as well.

My next hunch is that you ran into a bug somewhere. Could you filter all of your logs (including the gzipped ones) for the channel `fc89d1a6bd53b76d35e557e070b8f4740639f00b76c5e859db5658678f69b8ff`?

**Comment by Roasbeef** [comment]
Closing due to lack of updates.
