### ISSUE TITLE
Wallet Unlocker & LND in race condition 

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#4500]
### Background

On iOS (13.2) LND is requiring password input to unlock wallet. Password cannot be supplied without RPC. Wallet unlock can be added to "onResponse" callback when RPC is ready. However, RPC is never ready, without first supplying the wallet unlock password. Sustained wait leads to attached log and error (i.e. translating to a "leaking" promise in GRPC parlance)

This issue is related to many other issues before it, importantly #3982 

### Your environment

* version of `lnd`  ---  0.11.99-beta
* which operating system (`uname -a` on *Nix) ---- iOS 13.2
* version of `btcd`, `bitcoind`, or other backend  --- Neutrino 
* any other relevant environment details

### Steps to reproduce

Build Lndmobile.framework using gomobile. Add to iOS project. Start up LND. Listen to RPCReady "onResponse".  Execution never reaches the callback. Instead it crashes with attached error

### Expected behaviour

For RPC and Wallet Unlocker to work independently using "dummy" services as described in #3982 and for users to be able to input wallet password successfully and then for LND to start up normally.

### Actual behaviour

Crash due to **"leaking" promise** 

###LOG

2020-08-03 18:34:00.974 [INF] BTCN: Registering block subscription: id=1
2020-08-03 18:34:00.974 [INF] BTCN: Broadcaster now active
2020-08-03 18:34:00.976 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8001
2020-08-03 18:34:00.977 [INF] RPCS: password RPC server listening on bufconn
2020-08-03 18:34:00.977 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2020-08-03 18:34:00.998 [ERR] BTCN: Unable to parse IP network for peer nkf5e6b7pl4jfd4a.onion:18333: unsupported IP type
RPCReady LNDMobile callback : Response from RPC ready =  nil
Calling unlock wallet after RPC is ready
2020-08-03 18:34:01.040 [INF] BTCN: 6 addresses found from DNS seed testnet-seed.bluematt.me
2020-08-03 18:34:01.177 [INF] BTCN: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: no such host
2020-08-03 18:34:01.295 [INF] BTCN: New valid peer 34.210.154.40:18333 (outbound) (/Satoshi:0.18.99/)
2020-08-03 18:34:01.296 [INF] BTCN: Waiting for more block headers, then will start cfheaders sync from height 1802973...
2020-08-03 18:34:01.296 [INF] BTCN: Starting cfheaders sync from (block_height=1802973, block_hash=0000000000000fbc0b944e999463059714531028862cadacaf042ee063fae098) to (block_height=1802973, block_hash=0000000000000fbc0b944e999463059714531028862cadacaf042ee063fae098)
2020-08-03 18:34:01.297 [INF] BTCN: Starting cfheaders sync for filter_type=0
2020-08-03 18:34:01.313 [INF] BTCN: Syncing to block height 1803037 from peer 34.210.154.40:18333
2020-08-03 18:34:01.313 [INF] BTCN: Fetching set of headers from tip (height=1802973) from peer 34.210.154.40:18333
2020-08-03 18:34:01.341 [INF] BTCN: New valid peer 140.82.3.244:18333 (outbound) (/Satoshi:0.19.99/)
2020-08-03 18:34:01.349 [INF] BTCN: DNS discovery failed on seed testnet-seed.bitcoin.schildbach.de: lookup testnet-seed.bitcoin.schildbach.de: no such host
2020-08-03 18:34:02.005 [INF] BTCN: 8 addresses found from DNS seed x49.testnet-seed.bitcoin.jonasschnelli.ch
2020-08-03 18:34:02.123 [INF] BTCN: Fetching set of checkpointed cfheaders filters from height=1802973, hash=c9a4f3a3db668e18891c47483f95954d172a854f50a9d30de1c1d11e806cb138
2020-08-03 18:34:02.123 [INF] BTCN: Starting to query for cfheaders from checkpoint_interval=1802, checkpoints=1802
2020-08-03 18:34:02.134 [INF] BTCN: Fully caught up with cfheaders at height 1802973, waiting at tip for new blocks
2020-08-03 18:34:02.134 [INF] BTCN: Attempting to fetch set of un-checkpointed filters at height=1803037, hash=000000000000035ae2b813ab452dc6ede506116cd7b3bc88f5031654310e1fe4
ERROR: Cannot schedule tasks on an EventLoop that has already shut down. This will be upgraded to a forced crash in future SwiftNIO versions.
ERROR: Cannot schedule tasks on an EventLoop that has already shut down. This will be upgraded to a forced crash in future SwiftNIO versions.
Fatal error: **leaking promise** created at (file:

**Comment by halseth** [comment]
Are you saying you are not unlocking the wallet, and this happens?

**Comment by weaklysubjective** [comment]
Yes. 
I had previously mentioned control never reaches callback, but this is not correct. Control *does* reach RPCReady callback (that is , the call to LndmobileStart succeeds and control reaches "onResponse" callback. It is from there UnlockWallet is called resulting in the crash as above.

**Comment by weaklysubjective** [comment]
Wallet unlocks correctly ! But RPC is not ready. Thus subsequent call to supply password to open wallet fails. I do apologize for getting it backwards in my description above. In the steps to reproduce , It should have said , "listen to unlock wallet's 'on response'".

It may be that my RPC parameters are not correct and that is probably why RPC is not ready. I'll check this and report back. If all is well i will close this out. Thanks

**Comment by weaklysubjective** [comment]
Hi, I wanted to confirm, that when LND is started, it starts the Wallet unlocker Service successfully, and control reaches UnlockerReady callback. Subsequent call to UnlockerClient with wallet's password results in the reported crash. It is my lack of understanding that i referenced RPCReady.  It doesn't appear to have anything to do with the RPCReady callback.

**Comment by halseth** [comment]
maybe fixed by #4504 ?

**Comment by weaklysubjective** [comment]
Unfortunately 4504 did not fix it. To be clear, I did not checkout #4504 commit , instead edited gen_bindings.sh script, included the suggested changes , and rebuilt Lndmobile framework for iOS. Still on 0.10.99-beta.

Also, got around the RPC Wallet unlocker by calling unlocker natively. So, there is a workaround for now.

**Comment by halseth** [comment]
> Also, got around the RPC Wallet unlocker by calling unlocker natively. So, there is a workaround for now.

What does this mean? 

I'm sorry, I'm still trying to understand what the issue is exactly.

**Comment by halseth** [comment]
ping @weaklysubjective

**Comment by weaklysubjective** [comment]
Hey Johan,

Sorry about leaving this hanging. I really can't remember now how i got around this. But my best guess is that my use of the Lndmobile RPC was incorrect. I assumed the Lnrpc_xxxx were the api's and this resulted in errors. 
Whereas calling the methods in Lndmobile binary seemed to work. 
Let me think about this a bit more and PM you when i can describe it correctly.
