### ISSUE TITLE
Channel Close Issue

### ISSUE THREAD

**Issue by emretezel** [lightningnetwork/lnd#6063]
Hi Everyone,

A peer of mine has force closed the channel, and I see the transaction already included in a past block, but I still don't see closed local balance on my onchain wallet after a week almost. The transaction ID is

38ce2e0f95546f9783649febb910c71fb34a6ef1e2ee031f8d93fff2d97a93f5

https://mempool.space/tx/38ce2e0f95546f9783649febb910c71fb34a6ef1e2ee031f8d93fff2d97a93f5

Probably a very simple newbie question but any help greatly appreciated.

**Comment by guggero** [comment]
It looks like all those outputs have been swept by your node already. What does `lncli pendingchannels` show? Or the log? What chain backend (and pruned or full archival) node are you using?
Most likely a restart should fix this.

**Comment by emretezel** [comment]
lncli still shows the channels pending close (I have two cases), please see below


./lncli pendingchannels
{
    "total_limbo_balance": "8038935",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "035352d5960c7f86263e079f29707144088709332e781246b306370ca7e0a64183",
                "channel_point": "0c9354acd9ec02d1c6efbce14a900e33461bd86a8bcde09181efdd6a5ce45129:1",
                "capacity": "5000000",
                "local_balance": "3092420",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0"
            },
            "closing_txid": "38ce2e0f95546f9783649febb910c71fb34a6ef1e2ee031f8d93fff2d97a93f5",
            "limbo_balance": "3492424",
            "maturity_height": 713087,
            "blocks_til_maturity": 210,
            "recovered_balance": "330",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "400004",
                    "outpoint": "1ec2b4dac0a3b440c2ae2af69b8fe260745414c8270a9a12ae8c4bc0fe79f334:0",
                    "maturity_height": 713191,
                    "blocks_til_maturity": 314,
                    "stage": 2
                }
            ],
            "anchor": "RECOVERED"
        }
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "0256bf97644dd1d839aadd76e2351c1b6bb8173bb9f5ea4affb07075f880e52302",
                "channel_point": "d6bffe0291c4f8a9417cd03e0edd8ffa87a0fedd060fd3fa43c1cf36f7cbb737:1",
                "capacity": "5000000",
                "local_balance": "4546511",
                "remote_balance": "450242",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0"
            },
            "limbo_balance": "4546511",
            "commitments": {
                "local_txid": "862b84b40247336789def748c0ebcd68b8c138fff27b6fe81d2bf492e755868f",
                "remote_txid": "83fcc27dd414896810a0bbc4c030dfc1f8f170b3e97fe570fa0af9f8d0fd2cc7",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "2586",
                "remote_commit_fee_sat": "2586",
                "remote_pending_commit_fee_sat": "0"
            }
        }
    ]
}

**Comment by emretezel** [comment]
Hi,

I am running lnd-v0.14.1 with bitcoind using Umbrel latest version.

It shows 100% synced, restart didn't help.

Any workarounds much appreciated.

Best,
Emre

**Comment by guggero** [comment]
Can you please provide the logs since the last restart?

**Comment by emretezel** [comment]
[debug.log](https://github.com/lightningnetwork/lnd/files/7663534/debug.log
[lnd.log](https://github.com/lightningnetwork/lnd/files/7663535/lnd.log)
)

Hi there, please see attached logs of both bitcoin core and end after a fresh restart.

**Comment by guggero** [comment]
It looks like the chain channel resolved itself after the restart (when the chain needs to be rescanned, this usually takes some time):

```
2021-12-06 16:01:33.364 [INF] NTFN: Historical spend dispatch finished for request outpoint=38ce2e0f95546f9783649febb910c71fb34a6ef1e2ee031f8d93fff2d97a93f5:0, script=0 1e89dedad975bcca746358f0ba07ddc16b283d8cdeac9f091ebb475d5de8de73 (start=712488 end=712897) with details: 0dbebc1cffcf7373a8dc56d62a0077d696100b85690e1f95c45db0e618717a62[0] spending 38ce2e0f95546f9783649febb910c71fb34a6ef1e2ee031f8d93fff2d97a93f5:0 at height=712488
2021-12-06 16:01:33.377 [INF] NTFN: Dispatching confirmed spend notification for outpoint=38ce2e0f95546f9783649febb910c71fb34a6ef1e2ee031f8d93fff2d97a93f5:0, script=0 1e89dedad975bcca746358f0ba07ddc16b283d8cdeac9f091ebb475d5de8de73 at current height=712897: 0dbebc1cffcf7373a8dc56d62a0077d696100b85690e1f95c45db0e618717a62[0] spending 38ce2e0f95546f9783649febb910c71fb34a6ef1e2ee031f8d93fff2d97a93f5:0 at height=712488
2021-12-06 16:01:33.377 [INF] NTFN: Canceling spend notification: spend_id=20, outpoint=38ce2e0f95546f9783649febb910c71fb34a6ef1e2ee031f8d93fff2d97a93f5:0, script=0 1e89dedad975bcca746358f0ba07ddc16b283d8cdeac9f091ebb475d5de8de73
2021-12-06 16:01:33.391 [INF] CNCT: ChannelArbitrator(0c9354acd9ec02d1c6efbce14a900e33461bd86a8bcde09181efdd6a5ce45129:1): a contract has been fully resolved!
2021-12-06 16:01:33.391 [INF] CNCT: ChannelArbitrator(0c9354acd9ec02d1c6efbce14a900e33461bd86a8bcde09181efdd6a5ce45129:1): still awaiting contract resolution
```

What does the channel now show in `lncli pendingchannels`? Did it disappear?

**Comment by emretezel** [comment]
Hi there,

One of the transactions disappeared, but the one where the other party force closed still shows under pending

(pysystemtrade-1.03) emre@emre-OptiPlex-3080:~/umbrel/bin$ ./lncli pendingchannels
{
    "total_limbo_balance": "400004",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "035352d5960c7f86263e079f29707144088709332e781246b306370ca7e0a64183",
                "channel_point": "0c9354acd9ec02d1c6efbce14a900e33461bd86a8bcde09181efdd6a5ce45129:1",
                "capacity": "5000000",
                "local_balance": "3092420",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0"
            },
            "closing_txid": "38ce2e0f95546f9783649febb910c71fb34a6ef1e2ee031f8d93fff2d97a93f5",
            "limbo_balance": "400004",
            "maturity_height": 713087,
            "blocks_til_maturity": -28,
            "recovered_balance": "3092750",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "400004",
                    "outpoint": "1ec2b4dac0a3b440c2ae2af69b8fe260745414c8270a9a12ae8c4bc0fe79f334:0",
                    "maturity_height": 713191,
                    "blocks_til_maturity": 76,
                    "stage": 2
                }
            ],
            "anchor": "RECOVERED"
        }
    ],
    "waiting_close_channels": [
    ]
}

**Comment by emretezel** [comment]
Once the pending HTLCs expired, all channels closed, no more pending. The issue could that I have a rebalance script that runs every hour, it could have been that these channels were closed at the same time with some live rebalancing transactions.

Anyway good to see the system is very robust no bitcoin is lost.
