### ISSUE TITLE
[bug]: Despite updating node to v0.17.4, sync loss persist and channels can't connect after restart.

### ISSUE THREAD

**Issue by Megasley** [lightningnetwork/lnd#8489]
### Background

My node had the same loss sync issue that has just been fixed. Unfortunately, I wasn't aware of the v0.17.4 fix early enough. So, I used to restart the node to address the problem. However, the issue recurred, and despite restarting as usual, I realized the channels weren't connecting anymore. This led to force closures, resulting in a loss of 50% of the total channels.

I've been trying to figure out why, but I can't. I installed the new version, hoping it would fix the issue, but it hasn't.

### Your environment

* version of `lnd` - 0.17.4
* which operating system - ubuntu 20.04
* version of `btcd`, `bitcoind`, or other backend - bitcoind v24.99.0
* any other relevant environment details - I am running a pruned node set to 1000

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Expected node to stay synced to chain as long as backend stays synced and also channels to reconnect automatically on restart.

### Actual behaviour

Node loss sync every now and then and can only reconnect after restart. On restart, channel refuses to reconnect and come online.

Here's the most recent log of the node after restarting.

[lnd.log](https://github.com/lightningnetwork/lnd/files/14334908/lnd.log)

**Comment by ziggie1984** [comment]
Can you check your bitcoind data, how many peers are connected and what are the ping times ? Moreover how do you check that you are out of sync, lncli `getinfo` ?

**Comment by ziggie1984** [comment]
Can you also switch of the Watchtower client for now to make sure we can analyse the problem in an isolated way. According to the logs it seems like the Watchtower updates don't happen anyway.

**Comment by Megasley** [comment]
> Can you check your bitcoind data, how many peers are connected and what are the ping times ? Moreover how do you check that you are out of sync, lncli `getinfo` ?

I am connected to 122 peers

Yes, I use `lncli getinfo` to check. And aside that, I use thunderhub as a node monitoring software, so whenever it's out of sync, it's always visible there.

**Comment by Megasley** [comment]
> Can you also switch of the Watchtower client for now to make sure we can analyse the problem in an isolated way. According to the logs it seems like the Watchtower updates don't happen anyway.

I'll do that now.

**Comment by Megasley** [comment]
Disabled watchtower and restarted node

**Comment by ziggie1984** [comment]
yes could you also set the entire log to debug for the subsytems before sharing ?

**Comment by Megasley** [comment]
[logs.txt](https://github.com/lightningnetwork/lnd/files/14343259/logs.txt)

@ziggie1984 This is the new logs

**Comment by ziggie1984** [comment]
Can you provide a goroutine dump when your system is out of sync: `sudo curl -s  http://localhost:PORT_EDIT/debug/pprof/goroutine?debug=2`

you need to set it in the config setting: 

profile=PORT_EDIT

**Comment by Megasley** [comment]
> Can you provide a goroutine dump when your system is out of sync: `sudo curl -s http://localhost:PORT_EDIT/debug/pprof/goroutine?debug=2`
> 
> you need to set it in the config setting:
> 
> profile=PORT_EDIT

By config settings, do you mean lnd.config file?

**Comment by Megasley** [comment]
> exactly



> Can you provide a goroutine dump when your system is out of sync: `sudo curl -s http://localhost:PORT_EDIT/debug/pprof/goroutine?debug=2`
> 
> you need to set it in the config setting:
> 
> profile=PORT_EDIT

I did this but nothing happened.

We've lost almost all the channels.
Just 4 remaining.

[lnd.log](https://github.com/lightningnetwork/lnd/files/14371240/lnd.log)

**Comment by guggero** [comment]
It looks like your `bitcoind` only has 3 peers and they are all slow to respond. Make sure you have enough fast outbound peers on your bitcoin node. If necessary, increase the allowed number and connect some peers manually.
Because you are running with such a low prune value, `lnd` needs to fetch a lot of blocks during rescans. It does that using `bitcoind`'s peers. And if they don't give you the blocks or are too slow, `lnd` cannot sync.

**Comment by Megasley** [comment]
> It looks like your `bitcoind` only has 3 peers and they are all slow to respond. Make sure you have enough fast outbound peers on your bitcoin node. If necessary, increase the allowed number and connect some peers manually. Because you are running with such a low prune value, `lnd` needs to fetch a lot of blocks during rescans. It does that using `bitcoind`'s peers. And if they don't give you the blocks or are too slow, `lnd` cannot sync.

Would you advise I increase the prune value too?

**Comment by guggero** [comment]
If you have the disk space then definitely. Though I think it won't take effect immediately as it will just stop deleting blocks when new one come in until the new prune value is reached. But the low prune value is what's causing the issue in the first place (meaning all blocks need to be fetched from p2p, making your node dependent on your peers).

**Comment by guggero** [comment]
Oh, I guess this setting also needs to be bumped in `lnd`: [`bitcoind.pruned-node-max-peers`](https://github.com/lightningnetwork/lnd/blob/16279765eb192f20dce968db6fc57d1190dc9ba9/sample-lnd.conf#L769). Not sure what value to set it to, maybe the same as you have outbound peers configured in `bitcoind`?

**Comment by Megasley** [comment]
> If you have the disk space then definitely. Though I think it won't take effect immediately as it will just stop deleting blocks when new one come in until the new prune value is reached. But the low prune value is what's causing the issue in the first place (meaning all blocks need to be fetched from p2p, making your node dependent on your peers).

I will increase it to 3000.
I checked and bitcoind is connected to 123 peers.

**Comment by Megasley** [comment]
> bitcoind.pruned-node-max-peers

How do I do this actually pls?

**Comment by ziggie1984** [comment]
what port number did you use for ?

profile=???

Did you do this then:

`sudo curl -s  http://localhost:????/debug/pprof/goroutine?debug=2 > goroutine_dump.txt `

**Comment by Megasley** [comment]
> what port number did you use for ?
> 
> profile=???
> 
> Did you do this then:
> 
> `sudo curl -s http://localhost:????/debug/pprof/goroutine?debug=2 > goroutine_dump.txt `

`profile=10009`

I used port 1009

**Comment by guggero** [comment]
That port is already occupied by the RPC server, so it likely failed to start the profiler.

**Comment by Megasley** [comment]
> That port is already occupied by the RPC server, so it likely failed to start the profiler.

So I will have to use an entirely different port then.

**Comment by Megasley** [comment]
> Yes.

Done. Here's what I got

[goroutine.txt](https://github.com/lightningnetwork/lnd/files/14372059/goroutine.txt)

**Comment by eliotcougar** [comment]
I confirm... It looks like the sync loss still happens... Just noticed two channels force-closed a couple days ago with `failing link: unable to complete dance with error: remote unresponsive` errors... Usually I restarted my node once or twice a week, but this time it was running for three weeks without restart - and here's the result...

**Comment by ziggie1984** [comment]
> I confirm... It looks like the sync loss still happens... Just noticed two channels force-closed a couple days ago with failing link: unable to complete dance with error: remote unresponsive errors... Usually I restarted my node once or twice a week, but this time it was running for three weeks without restart - and here's the result...

Megasley is suffering from a startup issue, so could you be more specific about your case, when does it happen and can you provide the goroutine dump + logs when the out_of_sync happens ?

**Comment by eliotcougar** [comment]
> Megasley is suffering from a startup issue, so could you be more specific about your case, when does it happen and can you provide the goroutine dump + logs when the out_of_sync happens ?

I think I misread the title of the bug... I don't monitor my node closely and don't catch the issue when that happens… In the past I had issues with AfricaFreeRouting nodes force-closing often... Now the last two channels to their nodes are in the process of force-closing... I thought the issue was fixed... Sometimes I noticed that channel was offline, but only for me... I restarted my node, and it instantly was back online... I guess this time when I didn't notice it timed out and force-closed...

So, I'm sorry, but I'm not in the right situation for debugging it... All I know is that sometimes a node may go offline, I see `failing link: unable to complete dance with error: remote unresponsive` in the log around the time that happens, the remote node itself is online and reachable, but my node can't reestablish connection to it until I restart LND...

I only have WARN level logs, but there's nothing suspicious in them except that one type of error related to the force-closing channels...
