### ISSUE TITLE
Loading config file error

### ISSUE THREAD

**Issue by ghanavati27** [lightningnetwork/lnd#859]
I updated my lnd daemon from source code and also replaced my lnd.conf with new version of it.
after running lnd.exe i got this error:
"loadConfig: either bitcoin.active or litecoin.active must be set to 1 (true)"
my lnd.conf is attacked , please take a look it.
[lnd.conf.zip](https://github.com/lightningnetwork/lnd/files/1818614/lnd.conf.zip)

**Comment by halseth** [comment]
How are you running `lnd`? Are you specifying any additional flags?

I see that you have 
```
bitcoin.active=1
```
as the only option without a leading space. not sure why it should matter, but you could try adding it 😛

**Comment by ghanavati27** [comment]
@halseth , I running lnd without any additional flag.
Also , i tested with leading space and without it , same result.

**Comment by polkhovsky** [comment]
A suggestion, if I may: run `lnd --debuglevel=trace --bitcoin.active --bitcoing.testnet` to see what issue you may have in your lnd.conf file.

**Comment by ghanavati27** [comment]
@polkhovsky , please see https://github.com/lightningnetwork/lnd/issues/860

**Comment by polkhovsky** [comment]
So then this issue is resolved?

**Comment by ghanavati27** [comment]
No , this issue not fixed.
But when using a flags instead lnd.conf , i have this issue: https://github.com/lightningnetwork/lnd/issues/860
Also, when i using a clean conf file (see my config file at  https://github.com/lightningnetwork/lnd/issues/861) lnd will run successfully.

**Comment by Roasbeef** [comment]
You need to specify what chain you're running. Also check that you don't have any typos in the args that you're passing.

**Comment by dotneet** [comment]
I had same error and resolved it for remove an incorrect property from lnd.conf.
this error can be reproduced by adding not existed property like this:

```ini
[Application Options]
hohoho=hohoho
```
